import type { Beach, FarmerMarket, GolfCourse, ItineraryDay, MadeInHawaiiLocation, Place, RoutePlan, Suggestion, Trail, TripComment } from "@/lib/types";

export const tripStart = process.env.NEXT_PUBLIC_TRIP_START ?? "2026-05-22T00:00:00-10:00";

export const resort = {
  name: "Marriott's Ko Olina Beach Club",
  address: "92-161 Waipahe Place, Kapolei, HI 96707",
  checkIn: "May 22",
  checkOut: "May 29",
  note: "Most breakfasts will be at the resort before heading out for activities."
};

export const days: ItineraryDay[] = [
  {
    id: "fri-arrival",
    date: "Friday, May 22",
    title: "Arrival + Resort Relaxation",
    theme: "Land softly, stock up, and let the resort do the work.",
    wakeUp: "Travel day — keep it gentle after landing at 12:10 PM.",
    hero: "https://commons.wikimedia.org/wiki/Special:FilePath/Ko%20Olina%20Sunset.jpg?width=1600",
    difficulty: "Flexible",
    walking: "0.5-1.5 miles",
    teenFriendly: true,
    noPermit: true,
    driveTime: "HNL to resort: 25-40 min without traffic",
    parking: "Use Costco first, then resort valet/self-parking after check-in.",
    crowdTip: "Avoid adding a second destination; save energy for the week.",
    trail: "Sunset lagoon walk",
    beach: "Ko Olina lagoon",
    food: ["Costco provisions", "Monkeypod Kitchen", "Longboards Bar & Grill"],
    optional: ["Pool time", "Beach chairs", "Sunset photos", "Casual dinner"],
    tags: ["Relaxing", "Low crowds", "Scenic"],
    weatherNote: "Leeward west side is typically dry and sunny — great for a relaxed arrival.",
    tradeWindFriendly: false,
    crowdLevel: "Low",
    parkingDifficulty: "Easy",
    activityIcons: ["beach", "scenic"],
    schedule: [
      { time: "12:10 PM", plan: "Airport arrival, rental car pickup, and luggage load." },
      { time: "Afternoon", plan: "Costco/Target stop for snacks, waters, reef-safe sunscreen, and breakfast basics." },
      { time: "Check-in", plan: "Settle into Marriott's Ko Olina Beach Club." },
      { time: "Sunset", plan: "Relax at the resort beach or pool, then take a lagoon walk." }
    ]
  },
  {
    id: "sat-lanikai",
    date: "Saturday, May 23",
    title: "Kalawahine Hike + Lanikai Beach",
    theme: "Postcard Hawaii: best sunshine day — ridge trail views then turquoise water.",
    wakeUp: "Leave Ko Olina by 5:45–6:00 AM. Lanikai street parking fills before 8:30 AM.",
    hero: "https://commons.wikimedia.org/wiki/Special:FilePath/Lanikai%20Beach.jpg?width=1600",
    difficulty: "Easy-Moderate",
    walking: "3-5 miles total (trail + beach)",
    teenFriendly: true,
    noPermit: true,
    driveTime: "Ko Olina to Kalawahine trailhead: 55-70 min; trailhead to Lanikai: ~15 min",
    parking: "Arrive Lanikai by 8:30 AM MAX. Street parking on Mokulua Dr only — fills extremely fast.",
    crowdTip: "This is the BEST likely turquoise-water day. Saturday conditions are optimal — protect this plan.",
    trail: "Kalawahine Trail",
    beach: "Lanikai Beach",
    food: ["Kalapawai Market", "Boots & Kimo's"],
    optional: ["Tropical Farms Macadamias on drive back", "Kailua town stroll"],
    tags: ["Early morning", "Beach", "Scenic", "Teen friendly"],
    weatherNote: "Best likely sunny/turquoise-water day of the week. Saturday east-side skies are typically clearest.",
    bestLightingWindow: "8:45–11:30 AM — morning sun on Mokulua Islands is peak postcard lighting.",
    tradeWindFriendly: true,
    earlyStart: true,
    crowdLevel: "Medium",
    parkingDifficulty: "Hard",
    activityIcons: ["sunrise", "hike", "beach", "parking-caution"],
    schedule: [
      { time: "5:45 AM", plan: "Depart Ko Olina. Pack breakfast or grab coffee on the road." },
      { time: "6:45 AM", plan: "Kalawahine Trail — cool morning air, Ko'olau ridge views, shaded forest path." },
      { time: "8:15 AM", plan: "Trail complete. Drive ~15 min to Lanikai." },
      { time: "8:45 AM", plan: "Lanikai Beach — aim to be parked and on sand before 9 AM for best access and light." },
      { time: "11:30 AM", plan: "Wrap beach time before peak crowds and midday heat build." },
      { time: "Drive back", plan: "Optional: Tropical Farms Macadamias stop on the drive home toward Ko Olina." }
    ]
  },
  {
    id: "sun-waimanalo",
    date: "Sunday, May 24",
    title: "Judd Trail + Kailua Market + Waimānalo",
    theme: "Relaxed east-side day: jungle loop, local market, and a spacious beach.",
    wakeUp: "Leave by 7:00 AM for cooler trail conditions and market timing.",
    hero: "https://commons.wikimedia.org/wiki/Special:FilePath/Waimanalo%20Beach%20%2827829441405%29.jpg?width=1600",
    difficulty: "Easy-Moderate",
    walking: "2.5-4 miles total",
    teenFriendly: true,
    noPermit: true,
    driveTime: "Ko Olina to Judd Trail: 45-60 min; trail to Kailua Market: 15 min; Kailua to Waimānalo: 20 min",
    parking: "Judd Trail: street parking along Nuuanu Pali Dr. Kailua Market: arrive by 9 AM — fills quickly.",
    crowdTip: "East-side beaches are best earlier in the trip. Waimanalo stays uncrowded through midday.",
    trail: "Judd Trail",
    beach: "Waimānalo Beach",
    food: ["Mon Cha Cha Tea (Kailua market area)", "Kalapawai Market", "Fresh Catch"],
    optional: ["Kailua town browse", "Mānoa Chocolate", "Bayview Night Market (evening)"],
    tags: ["Waterfall", "Beach", "Market", "Teen friendly", "Scenic"],
    weatherNote: "East-side clouds are typical Sunday but pleasant. Waimanalo is sheltered and great most conditions.",
    bestLightingWindow: "11:00 AM–1:30 PM — Waimanalo faces east; morning and midday light is ideal.",
    tradeWindFriendly: true,
    crowdLevel: "Low",
    parkingDifficulty: "Moderate",
    activityIcons: ["hike", "market", "beach"],
    schedule: [
      { time: "7:00 AM", plan: "Depart Ko Olina with water and trail shoes." },
      { time: "8:00 AM", plan: "Judd Trail — short shaded jungle loop with stream crossings. 45-75 min." },
      { time: "9:00 AM", plan: "Drive to Kailua (15 min). Kailua Town Farmers Market (8 AM–12 PM)." },
      { time: "9:30 AM", plan: "Mon Cha Cha Tea stop in or near Kailua market area." },
      { time: "11:00 AM", plan: "Drive south to Waimānalo Beach (20 min)." },
      { time: "11:30 AM", plan: "Waimānalo Beach — spacious, low-key, great room to spread out." },
      { time: "1:30 PM", plan: "Easy drive back west. Optional Fresh Catch poke pickup on the way." }
    ]
  },
  {
    id: "mon-memorial",
    date: "Monday, May 25",
    title: "Lulumahu Falls + Halona Beach Cove",
    theme: "Jungle waterfall and scenic sea cove — avoiding Memorial Day North Shore crowds.",
    wakeUp: "Leave by 6:45 AM for cooler trail conditions and early Halona parking.",
    hero: "https://commons.wikimedia.org/wiki/Special:FilePath/Waimea%20Bay%20Beach%20%2812598985244%29.jpg?width=1600",
    difficulty: "Easy-Moderate",
    walking: "3-5 miles total",
    teenFriendly: true,
    noPermit: false,
    driveTime: "Ko Olina to Lulumahu: 40-55 min; Lulumahu to Halona: 25 min",
    parking: "Lulumahu: limited roadside near Nuuanu. Halona: small lot — arrive before 9:30 AM to secure a spot.",
    crowdTip: "DO NOT go to Waimea Bay on Memorial Day Monday. North Shore will be very crowded. This route stays calmer.",
    trail: "Lulumahu Falls Trail",
    beach: "Halona Beach Cove",
    food: ["Adela's Country Eatery", "Fresh Catch", "Kalapawai Market"],
    optional: ["Sandy Beach lookout", "Hanauma Bay scenic overlook", "Ko Olina evening swim"],
    tags: ["Waterfall", "Beach", "Early morning", "Scenic"],
    weatherNote: "Memorial Day Monday — intentionally avoiding North Shore crowds. East-side coastal route stays calmer.",
    bestLightingWindow: "9:30–11:30 AM — Halona Cove faces south/southeast with excellent morning light.",
    tradeWindFriendly: false,
    earlyStart: true,
    crowdLevel: "Medium",
    parkingDifficulty: "Hard",
    activityIcons: ["hike", "beach", "parking-caution", "scenic"],
    schedule: [
      { time: "6:45 AM", plan: "Depart Ko Olina — confirm Lulumahu permit logistics before leaving." },
      { time: "7:45 AM", plan: "Lulumahu Falls Trail — jungle creek trail with multiple stream crossings. ~1.5-2 hours." },
      { time: "9:00 AM", plan: "Trail complete. Drive to Halona Beach Cove (25 min)." },
      { time: "9:30 AM", plan: "Halona Beach Cove — scenic lava-framed cove, snorkeling, and stunning sea views." },
      { time: "11:30 AM", plan: "Wrap beach time. Optional Sandy Beach lookout nearby." },
      { time: "Afternoon", plan: "Easy drive back west. Adela's Country Eatery or Fresh Catch for lunch." }
    ]
  },
  {
    id: "tue-waimea",
    date: "Tuesday, May 26",
    title: "Waimea Bay + Dole Plantation",
    theme: "Premium North Shore day — intentionally moved off Memorial Day for better crowds and parking.",
    wakeUp: "Leave Ko Olina by 6:15 AM. Waimea Bay lot starts filling by 7:30 AM.",
    hero: "https://commons.wikimedia.org/wiki/Special:FilePath/Waimea%20Bay%20Oahu%20Hawaii%20Photo%20D%20Ramey%20Logan.jpg?width=1600",
    difficulty: "Easy",
    walking: "1-2 miles",
    teenFriendly: true,
    noPermit: true,
    driveTime: "Ko Olina to Waimea Bay: 45-60 min via H-2 North",
    parking: "⚠️ PARKING URGENCY: Arrive at Waimea Bay by 7:30–8:00 AM MAX. Small lot fills fast with no overflow on Tuesdays.",
    crowdTip: "Intentionally moved off Memorial Day. Tuesday crowds are noticeably lower — but still arrive early.",
    trail: "Optional short Waimea Valley walk",
    beach: "Waimea Bay",
    food: ["Giovanni's Shrimp Truck", "Coffee Gallery", "Dole Whip at Dole Plantation"],
    optional: ["Shark's Cove look", "Sunset Beach photo stop", "Haleʻiwa town browse"],
    tags: ["Beach", "Early morning", "Scenic", "Teen friendly"],
    weatherNote: "North Shore in May is typically calmer surf with clear water — excellent swimming conditions.",
    bestLightingWindow: "7:30–10:00 AM — early morning light on Waimea Bay is spectacular before crowds arrive.",
    tradeWindFriendly: true,
    earlyStart: true,
    crowdLevel: "Medium",
    parkingDifficulty: "Hard",
    activityIcons: ["sunrise", "beach", "parking-caution", "scenic"],
    schedule: [
      { time: "6:15 AM", plan: "Depart Ko Olina — EARLY departure is critical for parking." },
      { time: "7:30 AM", plan: "Arrive Waimea Bay. Target parking before 8:00 AM max." },
      { time: "8:00 AM", plan: "Waimea Bay beach time — swimming, cliff photos, watching local surfers." },
      { time: "11:30 AM", plan: "Wrap beach time. Depart before midday heat and return traffic." },
      { time: "12:30 PM", plan: "Giovanni's Shrimp Truck or Haleʻiwa town for lunch." },
      { time: "Drive south", plan: "Dole Plantation stop on the drive back — pineapple snacks and quick Dole Whip." }
    ]
  },
  {
    id: "wed-kualoa",
    date: "Wednesday, May 27",
    title: "Crouching Lion + Kualoa + Tropical Farms",
    theme: "Mountains, iconic coastline, and a relaxed evening at the Honolulu Farmers Market.",
    wakeUp: "Leave by 7:00 AM for morning trail and Kualoa arrival by 9:30 AM.",
    hero: "https://commons.wikimedia.org/wiki/Special:FilePath/Kailua%20Beach%20Park%20-%20Oahu%20-%20Hawaii.jpg?width=1600",
    difficulty: "Easy-Moderate",
    walking: "3-5 miles total",
    teenFriendly: true,
    noPermit: true,
    driveTime: "Ko Olina to Crouching Lion: 50-65 min; to Kualoa: 15 min; Kualoa to Tropical Farms: 15 min",
    parking: "Crouching Lion: roadside near trailhead. Kualoa Regional Park: large lot, usually available.",
    crowdTip: "Kualoa is a cloud-tolerant scenic day — the Ko'olau mountain backdrop is photogenic even with clouds.",
    trail: "Crouching Lion Trail (lower safe section only)",
    beach: "Kualoa Regional Park",
    food: ["Mon Cha Cha Tea (Honolulu Farmers Market area)", "Honolulu Farmers Market vendors", "Kakaʻako food options"],
    optional: ["Kualoa Ranch mountain views", "Chinaman's Hat island photos", "Evening Kakaʻako stroll"],
    tags: ["Scenic", "Beach", "Market", "Teen friendly", "Early morning"],
    weatherNote: "Cloud-tolerant day. Ko'olau mountain backdrop is dramatic even with clouds — flexible weather choice.",
    bestLightingWindow: "9:30 AM–12:30 PM at Kualoa — morning to midday light on mountains and bay.",
    tradeWindFriendly: true,
    crowdLevel: "Low",
    parkingDifficulty: "Easy",
    activityIcons: ["hike", "beach", "scenic", "market"],
    schedule: [
      { time: "7:00 AM", plan: "Depart Ko Olina toward windward coast." },
      { time: "8:00 AM", plan: "Crouching Lion Trail — LOWER SAFE SECTION ONLY. Ridge views over Kahana Bay." },
      { time: "8:30 AM", plan: "Trail complete. Drive to Kualoa Regional Park (15 min)." },
      { time: "9:30 AM", plan: "Kualoa Regional Park — beach, mountain views, and iconic Chinaman's Hat island." },
      { time: "12:30 PM", plan: "Wrap up Kualoa. Drive to Tropical Farms Macadamias (15 min)." },
      { time: "1:00 PM", plan: "Tropical Farms Macadamias — samples, local snacks, and gift shopping." },
      { time: "4:00 PM", plan: "Honolulu Farmers Market at Blaisdell Center (4–7 PM). Mon Cha Cha Tea stop #2." }
    ]
  },
  {
    id: "thu-resort",
    date: "Thursday, May 28",
    title: "Full Resort Recovery Day",
    theme: "Ko Olina lagoons, pool, shopping, relax, and sunset dinner.",
    wakeUp: "No alarm. Rest, recover, and enjoy the resort at your own pace.",
    hero: "https://commons.wikimedia.org/wiki/Special:FilePath/Aerial%20view%20of%20Disneys%20Aulani%20resort%20and%20Ko%20Olina%20Lagoon.jpg?width=1600",
    difficulty: "Flexible",
    walking: "As little or as much as wanted",
    teenFriendly: true,
    noPermit: true,
    driveTime: "Optional Kakaʻako outing: 35-55 min each way",
    parking: "Choose easy resort or nearby Kapolei options only.",
    crowdTip: "Protect the recovery day. One optional outing max — or none at all.",
    trail: "Lagoon walk",
    beach: "Ko Olina lagoons",
    food: ["Resort lunch", "Monkeypod Kitchen", "Sunset dinner"],
    optional: ["Spa", "Pool", "Shopping at Ka Makana Aliʻi", "Ko Olina Golf Club", "Made in Hawaii tasting stop"],
    tags: ["Relaxing", "Low crowds", "Beach"],
    weatherNote: "Leeward west side is typically drier and sunnier. Perfect weather for resort beach and pool.",
    tradeWindFriendly: false,
    crowdLevel: "Low",
    parkingDifficulty: "Easy",
    activityIcons: ["beach", "scenic"],
    schedule: [
      { time: "Morning", plan: "Sleep in. Spa, golf, pool, or Ko Olina lagoon walk." },
      { time: "Afternoon", plan: "Optional: shopping at Ka Makana Aliʻi or a Made in Hawaii tasting stop." },
      { time: "Evening", plan: "Sunset dinner and final relaxed evening at the resort." }
    ]
  },
  {
    id: "fri-departure",
    date: "Friday, May 29",
    title: "Departure Day",
    theme: "Easy breakfast, one last lagoon walk, then airport rhythm.",
    wakeUp: "Keep the morning open around your flight timing.",
    hero: "https://commons.wikimedia.org/wiki/Special:FilePath/Ko%20Olina%20Lagoon%20%28137451511%29.jpeg?width=1600",
    difficulty: "Flexible",
    walking: "0.5-1 mile",
    teenFriendly: true,
    noPermit: true,
    driveTime: "Ko Olina to HNL: 25-45 min depending on traffic",
    parking: "Build time for rental car return and luggage handling.",
    crowdTip: "Do not schedule a real outing on departure day.",
    trail: "Final lagoon walk",
    beach: "Ko Olina lagoon",
    food: ["Relaxed resort breakfast"],
    optional: ["Final family photo", "Grab airport snacks"],
    tags: ["Relaxing", "Beach", "Low crowds"],
    crowdLevel: "Low",
    parkingDifficulty: "Easy",
    activityIcons: ["beach"],
    schedule: [
      { time: "Morning", plan: "Relaxed breakfast and final packing." },
      { time: "Late morning", plan: "One last lagoon walk or pool sit." },
      { time: "Departure", plan: "Rental car return and airport departure." }
    ]
  }
];

export const places: Place[] = [
  { id: "resort", name: resort.name, category: "resort", address: resort.address, driveFromResort: "Home base", tags: ["Relaxing", "Beach"], lat: 21.3269, lng: -158.1206 },
  { id: "costco", name: "Costco Kapolei", category: "food", day: "Friday", address: "4589 Kapolei Pkwy, Kapolei, HI", driveFromResort: "12-18 min", tags: ["Arrival", "Groceries"], lat: 21.3327, lng: -158.0792 },
  // Saturday — Lanikai Day
  { id: "kalawahine", name: "Kalawahine Trail", category: "trail", day: "Saturday", address: "Kalawahine Trail, Tantalus, Honolulu, HI", driveFromResort: "55-70 min", tags: ["Scenic", "Ridge", "Early morning"], lat: 21.3317, lng: -157.8269 },
  { id: "lanikai", name: "Lanikai Beach", category: "beach", day: "Saturday", address: "Mokulua Dr, Kailua, HI", driveFromResort: "60-75 min", tags: ["Beach", "Scenic"], lat: 21.3925, lng: -157.7151 },
  { id: "boots", name: "Boots & Kimo's", category: "food", day: "Saturday", address: "1020 Keolu Dr, Kailua, HI", driveFromResort: "60-75 min", tags: ["Breakfast"], lat: 21.3788, lng: -157.7392 },
  { id: "kalapawai", name: "Kalapawai Market", category: "food", day: "Saturday", address: "306 S Kalaheo Ave, Kailua, HI", driveFromResort: "55-70 min", tags: ["Lunch", "Coffee"], lat: 21.3941, lng: -157.7439 },
  // Sunday — Waimanalo + Market
  { id: "judd", name: "Judd Trail", category: "trail", day: "Sunday", address: "Nuuanu Pali Dr, Honolulu, HI", driveFromResort: "45-60 min", tags: ["Waterfall", "Easy"], lat: 21.3601, lng: -157.8146 },
  { id: "kailua", name: "Kailua Beach", category: "beach", day: "Sunday", address: "526 Kawailoa Rd, Kailua, HI", driveFromResort: "55-70 min", tags: ["Beach", "Teen friendly"], lat: 21.3975, lng: -157.7278 },
  { id: "mon-cha-cha-tea-kailua", name: "Mon Cha Cha Tea (Kailua)", category: "food", day: "Sunday", address: "Kailua, HI", driveFromResort: "55-70 min", tags: ["Tea", "Market"], lat: 21.3951, lng: -157.7432 },
  { id: "waimanalo", name: "Waimānalo Beach", category: "beach", day: "Sunday", address: "41-741 Kalanianaole Hwy, Waimānalo, HI", driveFromResort: "55-75 min", tags: ["Beach", "Relaxing"], lat: 21.3367, lng: -157.7006 },
  { id: "fresh-catch", name: "Fresh Catch", category: "food", day: "Sunday", address: "3109 Waialae Ave, Honolulu, HI", driveFromResort: "35-50 min", tags: ["Lunch", "Poke"], lat: 21.2894, lng: -157.8081 },
  // Monday — Memorial Day / Halona
  { id: "lulumahu", name: "Lulumahu Falls Trail", category: "trail", day: "Monday", address: "Nuʻuanu, Honolulu, HI", driveFromResort: "40-55 min", tags: ["Permit required", "Waterfall", "Jungle"], lat: 21.3522, lng: -157.8139 },
  { id: "halona", name: "Halona Beach Cove", category: "beach", day: "Monday", address: "Halona Blowhole Lookout, Honolulu, HI 96825", driveFromResort: "50-65 min", tags: ["Beach", "Scenic", "Snorkeling"], lat: 21.2921, lng: -157.6750 },
  { id: "sandy", name: "Sandy Beach", category: "beach", day: "Monday", address: "8801 Kalanianaole Hwy, Honolulu, HI", driveFromResort: "50-70 min", tags: ["Beach", "Viewing"], lat: 21.2851, lng: -157.6722 },
  { id: "adelas", name: "Adela's Country Eatery", category: "food", day: "Monday", address: "41-865 Kalanianaole Hwy, Waimānalo, HI", driveFromResort: "55-75 min", tags: ["Lunch", "Local"], lat: 21.3352, lng: -157.7056 },
  // Tuesday — Waimea Bay
  { id: "waimea-bay", name: "Waimea Bay", category: "beach", day: "Tuesday", address: "61-031 Kamehameha Hwy, Haleiwa, HI", driveFromResort: "45-60 min", tags: ["Beach", "Scenic", "North Shore"], lat: 21.6408, lng: -158.0631 },
  { id: "waimea-valley", name: "Waimea Valley", category: "trail", day: "Tuesday", address: "59-864 Kamehameha Hwy, Haleiwa, HI", driveFromResort: "45-60 min", tags: ["Easy", "Waterfall"], lat: 21.6383, lng: -158.0503 },
  { id: "sharks-cove", name: "Shark's Cove", category: "beach", day: "Tuesday", address: "Pupukea, HI", driveFromResort: "50-65 min", tags: ["Adventure", "Beach"], lat: 21.6497, lng: -158.0636 },
  { id: "sunset-beach", name: "Sunset Beach", category: "beach", day: "Tuesday", address: "Sunset Beach, HI", driveFromResort: "55-70 min", tags: ["Scenic", "Beach"], lat: 21.6794, lng: -158.0417 },
  { id: "ululani-haleiwa", name: "Ululani's Hawaiian Shave Ice", category: "shaved-ice", day: "Tuesday", address: "Haleʻiwa, HI", driveFromResort: "35-50 min", tags: ["Shaved ice"], lat: 21.5923, lng: -158.1034 },
  { id: "giovannis", name: "Giovanni's Shrimp Truck", category: "food", day: "Tuesday", address: "66-472 Kamehameha Hwy, Haleiwa, HI", driveFromResort: "40-55 min", tags: ["Shrimp trucks", "Lunch"], lat: 21.5931, lng: -158.1037 },
  { id: "coffee-gallery", name: "Coffee Gallery", category: "food", day: "Tuesday", address: "66-250 Kamehameha Hwy, Haleiwa, HI", driveFromResort: "40-55 min", tags: ["Coffee"], lat: 21.5907, lng: -158.1046 },
  { id: "dole-plantation", name: "Dole Plantation", category: "food", day: "Tuesday", address: "64-1550 Kamehameha Hwy, Wahiawā, HI", driveFromResort: "25-35 min", tags: ["Pineapple", "Snacks"], lat: 21.5250, lng: -158.0370 },
  // Wednesday — Kualoa
  { id: "crouching-lion", name: "Crouching Lion Trail (lower section)", category: "trail", day: "Wednesday", address: "Crouching Lion Trailhead, Kāneʻohe, HI", driveFromResort: "50-65 min", tags: ["Scenic", "Ridge", "Easy"], lat: 21.5560, lng: -157.8620 },
  { id: "kualoa", name: "Kualoa Regional Park", category: "beach", day: "Wednesday", address: "49-479 Kamehameha Hwy, Kāneʻohe, HI", driveFromResort: "55-70 min", tags: ["Beach", "Scenic", "Mountains"], lat: 21.5100, lng: -157.8388 },
  { id: "tropical-farms-stop", name: "Tropical Farms Macadamias", category: "food", day: "Wednesday", address: "49-227 Kamehameha Hwy, Kāneʻohe, HI", driveFromResort: "55-70 min", tags: ["Macadamia", "Snacks", "Local"], lat: 21.5110, lng: -157.8450 },
  { id: "mon-cha-cha-tea-honolulu", name: "Mon Cha Cha Tea (Honolulu)", category: "food", day: "Wednesday", address: "Neal S. Blaisdell Center area, Honolulu, HI", driveFromResort: "35-50 min", tags: ["Tea", "Market"], lat: 21.3008, lng: -157.8506 },
  // Thursday / Friday
  { id: "turtle-bay-golf", name: "Turtle Bay Golf", category: "golf", day: "Tuesday", address: "57-091 Kamehameha Hwy, Kahuku, HI", driveFromResort: "65-85 min", tags: ["Golf", "Ocean Views", "North Shore"], lat: 21.7034, lng: -157.9974 },
  { id: "aloha-beer", name: "Aloha Beer Company", category: "brewery", day: "Thursday", address: "700 Queen St, Honolulu, HI", driveFromResort: "35-50 min", tags: ["Brewery", "Optional"], lat: 21.3012, lng: -157.8585 },
  { id: "kakaako-local-food", name: "Kakaʻako Local Food + Brewery Area", category: "made-in-hawaii", day: "Thursday", address: "Kakaʻako, Honolulu, HI", driveFromResort: "35-55 min", tags: ["Local food", "Brewery", "Made in Hawaii"], lat: 21.2984, lng: -157.8607 },
  // Retained legacy places for map/reference
  { id: "ono", name: "Ono Seafood", category: "food", day: "Sunday", address: "747 Kapahulu Ave, Honolulu, HI", driveFromResort: "35-50 min", tags: ["Lunch", "Poke"], lat: 21.2806, lng: -157.8137 },
  { id: "makapuu", name: "Makapuʻu Lighthouse Trail", category: "trail", day: "Reference", address: "Kalanianaole Hwy, Waimānalo, HI", driveFromResort: "55-75 min", tags: ["Easy", "Scenic"], lat: 21.3094, lng: -157.6492 },
  { id: "ululani-kailua", name: "Ululani's Hawaiian Shave Ice (Kailua)", category: "shaved-ice", day: "Sunday", address: "Kailua, HI", driveFromResort: "55-70 min", tags: ["Shaved ice"], lat: 21.3932, lng: -157.7435 },
  { id: "pali", name: "Pali Twin Falls", category: "trail", day: "Reference", address: "Nuʻuanu, Honolulu, HI", driveFromResort: "45-60 min", tags: ["Waterfall", "Adventure"], lat: 21.3629, lng: -157.8006 }
];

export const foodCategories = [
  "Local Hawaiian food",
  "Shrimp trucks",
  "Breakfast",
  "Lunch",
  "Dinner",
  "Shaved ice",
  "Coffee",
  "Breweries",
  "Farmers markets",
  "Poke",
  "Desserts"
];

export const beaches: Beach[] = [
  {
    id: "lanikai",
    name: "Lanikai Beach",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Lanikai%20Beach.jpg?width=1200",
    crowd: "High",
    parking: "Hard",
    snorkeling: "Light reef viewing",
    swimming: "Stunning turquoise water; parking and early arrival are critical",
    amenities: "No bathrooms/showers at beach access points",
    familyScore: 4,
    sunsetScore: 2,
    notes: "Best on Saturday — the optimal weather day. Arrive before 9 AM. Street parking on Mokulua Dr fills extremely fast.",
    tags: ["Scenic", "Beach", "Early morning", "Best weather day"]
  },
  {
    id: "waimanalo",
    name: "Waimānalo Beach",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Waimanalo%20Beach%20%2827829441405%29.jpg?width=1200",
    crowd: "Low",
    parking: "Medium",
    snorkeling: "Minimal",
    swimming: "Good room to spread out; check wind and shorebreak",
    amenities: "Bathrooms and showers at park areas",
    familyScore: 5,
    sunsetScore: 2,
    notes: "Sunday anchor beach. Spacious, low-key, and great for relaxed family time after the Kailua market.",
    tags: ["Low crowds", "Relaxing", "Beach"]
  },
  {
    id: "halona",
    name: "Halona Beach Cove",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Waimanalo%20Beach%20%2827829441405%29.jpg?width=1200",
    crowd: "Medium",
    parking: "Hard",
    snorkeling: "Good — protected cove when calm",
    swimming: "Check conditions; lava-framed cove with snorkeling when calm",
    amenities: "Small lot, no lifeguard — check conditions before entering",
    familyScore: 4,
    sunsetScore: 3,
    notes: "Monday Memorial Day beach. Arrive before 9:30 AM. Stunning scenic cove — a great alternative to busy North Shore.",
    tags: ["Scenic", "Beach", "Snorkeling", "Early morning"]
  },
  {
    id: "waimea",
    name: "Waimea Bay",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Waimea%20Bay%20Beach%20%2812598985244%29.jpg?width=1200",
    crowd: "High",
    parking: "Hard",
    snorkeling: "Seasonal — calm in May",
    swimming: "Generally calm in May — respect lifeguard guidance always",
    amenities: "Bathrooms and showers",
    familyScore: 4,
    sunsetScore: 4,
    notes: "Tuesday — intentionally moved off Memorial Day Monday. Arrive by 7:30–8:00 AM MAX for parking. Small lot fills very fast.",
    tags: ["North Shore", "Scenic", "Early morning", "Parking caution"]
  },
  {
    id: "kualoa",
    name: "Kualoa Regional Park",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Kailua%20Beach%20Park%20-%20Oahu%20-%20Hawaii.jpg?width=1200",
    crowd: "Low",
    parking: "Easy",
    snorkeling: "Minimal",
    swimming: "Calm shallow water; better for wading and scenery",
    amenities: "Bathrooms, picnic areas, large parking lot",
    familyScore: 5,
    sunsetScore: 3,
    notes: "Wednesday anchor. Iconic Ko'olau mountain backdrop and Chinaman's Hat island views. Cloud-tolerant and very photogenic.",
    tags: ["Scenic", "Low crowds", "Beach", "Mountains"]
  },
  {
    id: "kailua-beach",
    name: "Kailua Beach Park",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Kailua%20Beach%20Park%20-%20Oahu%20-%20Hawaii.jpg?width=1200",
    crowd: "Medium",
    parking: "Medium",
    snorkeling: "Light",
    swimming: "Generally family-friendly when conditions are calm",
    amenities: "Bathrooms, showers, picnic areas",
    familyScore: 5,
    sunsetScore: 2,
    notes: "Great alternative/overflow option near Lanikai. Easier parking than Lanikai.",
    tags: ["Beach", "Teen friendly", "Bathrooms"]
  },
  {
    id: "ko-olina",
    name: "Ko Olina Lagoons",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Ko%20Olina%20Lagoon%203.jpg?width=1200",
    crowd: "Medium",
    parking: "Easy",
    snorkeling: "Calm beginner-friendly water",
    swimming: "Protected lagoon setting",
    amenities: "Resort amenities nearby",
    familyScore: 5,
    sunsetScore: 5,
    notes: "Home base beach. Best recovery-day choice — easiest with all ages and stunning west-facing sunsets.",
    tags: ["Relaxing", "Sunset", "Family"]
  }
];

export const trails: Trail[] = [
  {
    id: "kalawahine",
    name: "Kalawahine Trail",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Rainforest_on_Manoa_Falls_trail,_Oahu,_Hawaii_-_panoramio.jpg?width=1200",
    distance: "~3 miles round trip",
    time: "75-90 min",
    difficulty: "Easy-Moderate",
    permit: "No permit",
    mud: "Low",
    streams: "No",
    crowd: "Low",
    parking: "Medium",
    nearbyFood: "Kalapawai Market, Boots & Kimo's",
    beachPairing: "Lanikai Beach",
    notes: "Saturday morning ridge trail on Tantalus with Ko'olau views. Cool early morning air makes this ideal before Lanikai.",
    tags: ["Ridge", "Scenic", "No permit", "Early morning"]
  },
  {
    id: "judd",
    name: "Judd Trail",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Rainforest_on_Manoa_Falls_trail,_Oahu,_Hawaii_-_panoramio.jpg?width=1200",
    distance: "1.0-1.5 miles",
    time: "45-75 min",
    difficulty: "Easy",
    permit: "No permit",
    mud: "Medium",
    streams: "Yes, small crossings",
    crowd: "Medium",
    parking: "Medium",
    nearbyFood: "Kailua or Honolulu lunch",
    beachPairing: "Waimānalo Beach",
    notes: "Short, shaded jungle loop with stream crossings. Best after checking recent rain. Pairs well with Sunday Kailua market.",
    tags: ["Waterfall", "Jungle", "Teen friendly", "No permit"]
  },
  {
    id: "lulumahu",
    name: "Lulumahu Falls Trail",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Waimea_Valley_Audubon_Center,_Oahu,_Hawaii_-_waterfall_view.JPG?width=1200",
    distance: "~2.5 miles",
    time: "1.5-2.5 hours",
    difficulty: "Moderate",
    permit: "Permit required",
    mud: "High",
    streams: "Multiple",
    crowd: "Medium",
    parking: "Hard",
    nearbyFood: "Adela's Country Eatery or Fresh Catch",
    beachPairing: "Halona Beach Cove",
    notes: "Monday Memorial Day hike. Confirm permit before departure. Jungle creek trail with multiple stream crossings. Pairs with Halona Beach Cove.",
    tags: ["Waterfall", "Permit required", "Jungle", "Early morning"]
  },
  {
    id: "crouching-lion",
    name: "Crouching Lion Trail (lower section)",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Kailua%20Beach%20Park%20-%20Oahu%20-%20Hawaii.jpg?width=1200",
    distance: "1-2 miles (lower section only)",
    time: "45-60 min",
    difficulty: "Easy-Moderate",
    permit: "No permit",
    mud: "Low",
    streams: "No",
    crowd: "Low",
    parking: "Medium",
    nearbyFood: "Tropical Farms Macadamias, Kualoa area",
    beachPairing: "Kualoa Regional Park",
    notes: "LOWER SAFE SECTION ONLY. Ridge views over Kahana Bay. Do not attempt upper sections. Wednesday morning warmup before Kualoa.",
    tags: ["Ridge", "Scenic", "No permit", "Low crowds"]
  },
  {
    id: "aihualama",
    name: "Aihualama Partial Route",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Manoa_falls_entrance_of_trail.jpg?width=1200",
    distance: "Up to 2.8 miles",
    time: "75-120 min",
    difficulty: "Easy-Moderate",
    permit: "No permit",
    mud: "High",
    streams: "Possible wet sections",
    crowd: "Medium",
    parking: "Medium",
    nearbyFood: "Ono Seafood or Fresh Catch",
    beachPairing: "Waimānalo Beach",
    notes: "Alternative jungle route if schedule shifts. Use a partial route to keep the day relaxed.",
    tags: ["Jungle", "Scenic", "No permit"]
  },
  {
    id: "pali-twin",
    name: "Pali Twin Falls Candidate",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Manoa_Falls_Hawaii.jpg?width=1200",
    distance: "Under 2 miles target",
    time: "60-90 min",
    difficulty: "Easy-Moderate",
    permit: "No permit",
    mud: "Medium",
    streams: "Likely",
    crowd: "Low",
    parking: "Medium",
    nearbyFood: "Kailua side",
    beachPairing: "Kailua or Waimānalo",
    notes: "Flexible waterfall option if schedule shifts. Low crowds and no permit required.",
    tags: ["Waterfall", "Low crowds", "No permit"]
  }
];

const marketPhoto = "https://commons.wikimedia.org/wiki/Special:FilePath/Kailua%20Beach%20Park%20-%20Oahu%20-%20Hawaii.jpg?width=1000";

export const farmerMarkets: FarmerMarket[] = [
  {
    id: "kekaulike-market",
    name: "Kekaulike Market in Chinatown",
    days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    hours: "7am-3pm",
    location: "Chinatown Honolulu",
    address: "1039 Kekaulike St, Honolulu, HI 96817",
    region: "Honolulu",
    lat: 21.3122,
    lng: -157.8629,
    photo: marketPhoto,
    nearby: { beaches: ["Ala Moana Beach Park"], trails: ["Aihualama / Mānoa Area"], food: ["Ono Seafood", "Fresh Catch"] },
    bestItineraryDays: ["Sunday", "Thursday"],
    recommendedStop: "Best as a city-side add-on after Mānoa or before Kakaʻako local food.",
    driveFromResort: "35-50 min",
    parkingWarning: "Chinatown parking can be tight; use garages and keep valuables out of sight."
  },
  {
    id: "city-square-marketplace",
    name: "Marketplace at City Square",
    days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    hours: "8am-4pm",
    location: "City Square Shopping Center",
    address: "1199 Dillingham Blvd, Honolulu, HI 96817",
    region: "Honolulu",
    lat: 21.3221,
    lng: -157.8758,
    photo: marketPhoto,
    nearby: { beaches: ["Ala Moana Beach Park"], trails: ["Aihualama / Mānoa Area"], food: ["Kakaʻako food stops"] },
    bestItineraryDays: ["Sunday", "Thursday"],
    recommendedStop: "Works on town days when the family is already crossing Honolulu.",
    driveFromResort: "30-45 min"
  },
  {
    id: "waikiki-makers-4",
    name: "Waikīkī Makers Market",
    days: ["Monday"],
    hours: "4-8pm",
    location: "Waikīkī",
    address: "2330 Kalākaua Ave, Honolulu, HI 96815",
    region: "Waikiki",
    lat: 21.2794,
    lng: -157.8293,
    photo: marketPhoto,
    nearby: { beaches: ["Waikīkī Beach"], trails: ["Diamond Head area"], food: ["Waikīkī restaurants"] },
    bestItineraryDays: ["Thursday"],
    recommendedStop: "Optional only if the family wants an evening Waikīkī outing.",
    driveFromResort: "40-65 min",
    parkingWarning: "Waikīkī parking and return traffic can be slow."
  },
  {
    id: "waikiki-farmers-hyatt",
    name: "Waikiki Farmers Market",
    days: ["Monday", "Wednesday"],
    hours: "4-8pm",
    location: "Hyatt Regency Waikiki Beach Resort",
    address: "2424 Kalākaua Ave, Honolulu, HI 96815",
    region: "Waikiki",
    lat: 21.2766,
    lng: -157.8257,
    photo: marketPhoto,
    nearby: { beaches: ["Waikīkī Beach"], trails: ["Diamond Head area"], food: ["Waikīkī restaurants"] },
    bestItineraryDays: ["Wednesday", "Thursday"],
    recommendedStop: "Evening city add-on; not ideal after North Shore.",
    driveFromResort: "40-65 min",
    parkingWarning: "Plan paid parking and avoid late-afternoon H-1 if possible."
  },
  {
    id: "waikiki-makers-5",
    name: "Waikiki Makers Market",
    days: ["Monday"],
    hours: "5-9pm",
    location: "Waikīkī",
    address: "2330 Kalākaua Ave, Honolulu, HI 96815",
    region: "Waikiki",
    lat: 21.2794,
    lng: -157.8293,
    photo: marketPhoto,
    nearby: { beaches: ["Waikīkī Beach"], trails: ["Diamond Head area"], food: ["Waikīkī restaurants"] },
    bestItineraryDays: ["Thursday"],
    recommendedStop: "Treat as an optional evening market if the group wants city energy.",
    driveFromResort: "40-65 min",
    parkingWarning: "Waikīkī parking can be expensive."
  },
  {
    id: "fort-street-open-market",
    name: "Fort Street Mall Open Market",
    days: ["Tuesday", "Friday"],
    hours: "7am-1:30pm",
    location: "Fort Street Mall",
    address: "Fort Street Mall, Honolulu, HI 96813",
    region: "Honolulu",
    lat: 21.3103,
    lng: -157.8608,
    photo: marketPhoto,
    nearby: { beaches: ["Ala Moana Beach Park"], trails: ["Aihualama / Mānoa Area"], food: ["Downtown lunch"] },
    bestItineraryDays: ["Friday", "Tuesday"],
    recommendedStop: "Useful if arriving/departing through town, but not worth a separate drive.",
    driveFromResort: "35-50 min"
  },
  {
    id: "makeke-iki-waianae",
    name: "Mākeke ʻIki at Waiʻanae",
    days: ["Tuesday"],
    hours: "9am-12pm",
    location: "Waiʻanae Coast Comprehensive Health Center",
    address: "86-260 Farrington Hwy, Waiʻanae, HI 96792",
    region: "West Side",
    lat: 21.4465,
    lng: -158.184,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Ko%20Olina%20Lagoon%203.jpg?width=1000",
    nearby: { beaches: ["Ko Olina Lagoons", "West side beaches"], trails: ["Lagoon walk"], food: ["Ko Olina restaurants"] },
    bestItineraryDays: ["Tuesday", "Wednesday", "Thursday"],
    recommendedStop: "Best west-side fit when staying close to Ko Olina.",
    driveFromResort: "25-35 min"
  },
  {
    id: "kaiser-ptsa",
    name: "Kaiser PTSA Farmers Market",
    days: ["Tuesday"],
    hours: "4-6pm",
    location: "Kaiser High School",
    address: "511 Lunalilo Home Rd, Honolulu, HI 96825",
    region: "East Honolulu",
    lat: 21.2872,
    lng: -157.7045,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Lanikai%20Beach.jpg?width=1000",
    nearby: { beaches: ["Sandy Beach", "Waimānalo Beach"], trails: ["Makapuʻu area"], food: ["East Honolulu casual food"] },
    bestItineraryDays: ["Tuesday"],
    recommendedStop: "Possible after east-side beach time, but only if the family is still nearby late afternoon.",
    driveFromResort: "55-75 min"
  },
  {
    id: "bayview-night-market",
    name: "Bayview Night Market",
    days: ["Tuesday"],
    hours: "4-8pm",
    location: "Bay View area, Kāneʻohe",
    address: "45-285 Kāneʻohe Bay Dr, Kāneʻohe, HI 96744",
    region: "Windward",
    lat: 21.407,
    lng: -157.798,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Kailua%20Beach%20Park%20-%20Oahu%20-%20Hawaii.jpg?width=1000",
    nearby: { beaches: ["Kailua Beach Park"], trails: ["Judd Trail", "Pali Twin Falls"], food: ["Kailua restaurants"] },
    bestItineraryDays: ["Saturday", "Tuesday"],
    recommendedStop: "Windward evening option if already returning from Kailua/Kāneʻohe.",
    driveFromResort: "45-65 min"
  },
  {
    id: "manoa-marketplace",
    name: "The Farmers Market at Mānoa Marketplace",
    days: ["Tuesday", "Thursday", "Sunday"],
    hours: "7am-2pm",
    location: "Mānoa Marketplace",
    address: "2752 Woodlawn Dr, Honolulu, HI 96822",
    region: "Honolulu",
    lat: 21.3099,
    lng: -157.8095,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Waimanalo%20Beach%20%2827829441405%29.jpg?width=1000",
    nearby: { beaches: ["Waimānalo Beach"], trails: ["Aihualama / Mānoa Area"], food: ["Ono Seafood", "Fresh Catch"] },
    bestItineraryDays: ["Sunday"],
    recommendedStop: "Excellent match for the Dole + Aihualama + Waimānalo day.",
    driveFromResort: "35-50 min",
    parkingWarning: "Arrive early for easier Mānoa parking."
  },
  {
    id: "aloha-stadium",
    name: "Aloha Stadium Swap Meet & Marketplace",
    days: ["Wednesday", "Saturday", "Sunday"],
    hours: "Wed/Sat 8am-3pm; Sun 6:30am-3pm",
    location: "Aloha Stadium",
    address: "99-500 Salt Lake Blvd, Aiea, HI 96701",
    region: "Central",
    lat: 21.3726,
    lng: -157.9298,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Ko%20Olina%20Lagoon%203.jpg?width=1000",
    nearby: { beaches: ["Ko Olina Lagoons", "Ala Moana Beach Park"], trails: ["Lagoon walk"], food: ["Pearlridge/Aiea food"] },
    bestItineraryDays: ["Wednesday", "Saturday"],
    recommendedStop: "Good central stop between Ko Olina and Honolulu/Windward routes.",
    driveFromResort: "20-30 min"
  },
  {
    id: "mini-artfest-marriott",
    name: "Mini Artfest at Marriott Ko Olina Beach Club",
    days: ["Wednesday", "Friday"],
    hours: "9am-4pm",
    location: "Marriott's Ko Olina Beach Club",
    address: resort.address,
    region: "West Side",
    lat: 21.3269,
    lng: -158.1206,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Aerial%20view%20of%20Disneys%20Aulani%20resort%20and%20Ko%20Olina%20Lagoon.jpg?width=1000",
    nearby: { beaches: ["Ko Olina Lagoons"], trails: ["Lagoon walk"], food: ["Monkeypod Kitchen", "Longboards Bar & Grill"] },
    bestItineraryDays: ["Wednesday", "Friday"],
    recommendedStop: "Best low-effort market because it is at the home base.",
    driveFromResort: "At resort"
  },
  {
    id: "north-shore-country",
    name: "North Shore Country Market",
    days: ["Wednesday"],
    hours: "1-6pm",
    location: "Sunset Beach area",
    address: "59-360 Kamehameha Hwy, Haleʻiwa, HI 96712",
    region: "North Shore",
    lat: 21.667,
    lng: -158.052,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Waimea%20Bay%20Beach%20%2812598985244%29.jpg?width=1000",
    nearby: { beaches: ["Sunset Beach", "Waimea Bay"], trails: ["Waimea Valley area"], food: ["North Shore Tacos", "Giovanni's Shrimp Truck"] },
    bestItineraryDays: ["Monday", "Wednesday"],
    recommendedStop: "North Shore fit, but the current North Shore day is Monday; use only if schedule shifts.",
    driveFromResort: "55-75 min",
    parkingWarning: "North Shore roadside parking can be slow and crowded."
  },
  {
    id: "windward-mall",
    name: "Farmers Market at Windward Mall",
    days: ["Wednesday", "Sunday"],
    hours: "Wed 2-6pm; Sun 10am-2pm",
    location: "Windward Mall",
    address: "46-056 Kamehameha Hwy, Kāneʻohe, HI 96744",
    region: "Windward",
    lat: 21.418,
    lng: -157.805,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Kailua%20Beach%20Park%20-%20Oahu%20-%20Hawaii.jpg?width=1000",
    nearby: { beaches: ["Kailua Beach Park"], trails: ["Judd Trail", "Pali Twin Falls"], food: ["Kailua restaurants"] },
    bestItineraryDays: ["Saturday", "Sunday", "Wednesday"],
    recommendedStop: "Good windward backup if Kailua parking or weather changes plans.",
    driveFromResort: "45-65 min"
  },
  {
    id: "honolulu-farmers",
    name: "Honolulu Farmers Market",
    days: ["Wednesday"],
    hours: "4-7pm",
    location: "Neal S. Blaisdell Center",
    address: "777 Ward Ave, Honolulu, HI 96814",
    region: "Honolulu",
    lat: 21.3008,
    lng: -157.8506,
    photo: marketPhoto,
    nearby: { beaches: ["Ala Moana Beach Park"], trails: ["Aihualama / Mānoa Area"], food: ["Kakaʻako restaurants"] },
    bestItineraryDays: ["Wednesday", "Thursday"],
    recommendedStop: "Easy pairing with Kakaʻako local food or brewery stops.",
    driveFromResort: "35-50 min"
  },
  {
    id: "makana-ka-makana",
    name: "Makana Mkt. at Ka Makana Aliʻi",
    days: ["Wednesday", "Saturday", "Sunday"],
    hours: "Wed 4-8pm; Sat/Sun 11am-3pm",
    location: "Ka Makana Aliʻi",
    address: "91-5431 Kapolei Pkwy, Kapolei, HI 96707",
    region: "West Side",
    lat: 21.331,
    lng: -158.0904,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Ko%20Olina%20Lagoon%203.jpg?width=1000",
    nearby: { beaches: ["Ko Olina Lagoons"], trails: ["Lagoon walk"], food: ["Kapolei restaurants"] },
    bestItineraryDays: ["Friday", "Wednesday", "Thursday"],
    recommendedStop: "Best west-side grocery/snack add-on near Ko Olina.",
    driveFromResort: "12-18 min"
  },
  {
    id: "kailua-thursday",
    name: "Kailua Farmers Market",
    days: ["Thursday"],
    hours: "4-7pm",
    location: "Kailua town",
    address: "609 Kailua Rd, Kailua, HI 96734",
    region: "Windward",
    lat: 21.3925,
    lng: -157.7426,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Kailua%20Beach%20Park%20-%20Oahu%20-%20Hawaii.jpg?width=1000",
    nearby: { beaches: ["Kailua Beach Park", "Lanikai Beach"], trails: ["Judd Trail", "Pali Twin Falls"], food: ["Kalapawai Market"] },
    bestItineraryDays: ["Saturday", "Tuesday"],
    recommendedStop: "Ideal if the family moves Kailua-side plans to Thursday evening.",
    driveFromResort: "55-70 min",
    parkingWarning: "Kailua town parking is easier than Lanikai but still fills at peak times."
  },
  {
    id: "ono-grindz-makeke",
    name: "Ono Grindz & Mākeke Farmers Market",
    days: ["Thursday"],
    hours: "4-8pm",
    location: "West/Central Oʻahu pop-up market",
    address: "94-790 Lumiaina St, Waipahu, HI 96797",
    region: "Central",
    lat: 21.403,
    lng: -158.007,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Ko%20Olina%20Lagoon%203.jpg?width=1000",
    nearby: { beaches: ["Ko Olina Lagoons"], trails: ["Lagoon walk"], food: ["Kapolei/Waipahu food"] },
    bestItineraryDays: ["Thursday"],
    recommendedStop: "Central/west option for resort recovery day without crossing to Waikīkī.",
    driveFromResort: "20-30 min"
  },
  {
    id: "mahiku-mililani",
    name: "Mahiku Farmers Market",
    days: ["Friday"],
    hours: "3-7pm",
    location: "Mililani Shopping Center",
    address: "95-221 Kipapa Dr, Mililani, HI 96789",
    region: "Central",
    lat: 21.4502,
    lng: -158.0171,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Waimea%20Bay%20Beach%20%2812598985244%29.jpg?width=1000",
    nearby: { beaches: ["North Shore beaches"], trails: ["Waimea area"], food: ["Mililani casual food"] },
    bestItineraryDays: ["Monday"],
    recommendedStop: "Central stop only if North Shore timing shifts later in the week.",
    driveFromResort: "35-45 min"
  },
  {
    id: "kcc",
    name: "KCC Farmers Market",
    days: ["Saturday"],
    hours: "7:30-11am",
    location: "Kapiʻolani Community College",
    address: "4303 Diamond Head Rd, Honolulu, HI 96816",
    region: "Honolulu",
    lat: 21.2687,
    lng: -157.8022,
    photo: marketPhoto,
    nearby: { beaches: ["Waikīkī Beach"], trails: ["Diamond Head area"], food: ["Ono Seafood", "Fresh Catch"] },
    bestItineraryDays: ["Saturday"],
    recommendedStop: "Saturday option, but it pulls the family toward town before Kailua; use only if everyone wants a food-first morning.",
    driveFromResort: "45-60 min",
    parkingWarning: "Very popular; arrive early."
  },
  {
    id: "kakaako",
    name: "Kakaʻako Farmers Market",
    days: ["Saturday"],
    hours: "8am-12pm",
    location: "Kakaʻako",
    address: "919 Ala Moana Blvd, Honolulu, HI 96814",
    region: "Honolulu",
    lat: 21.2952,
    lng: -157.8599,
    photo: marketPhoto,
    nearby: { beaches: ["Ala Moana Beach Park"], trails: ["Mānoa area"], food: ["Kakaʻako restaurants"] },
    bestItineraryDays: ["Saturday", "Thursday"],
    recommendedStop: "Better for a town day than Kailua day; keep as optional.",
    driveFromResort: "35-50 min",
    parkingWarning: "Popular Saturday market with urban parking."
  },
  {
    id: "pearlridge",
    name: "Pearlridge Farmers Market",
    days: ["Saturday"],
    hours: "8am-12pm",
    location: "Pearlridge Center",
    address: "98-1005 Moanalua Rd, Aiea, HI 96701",
    region: "Central",
    lat: 21.385,
    lng: -157.943,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Ko%20Olina%20Lagoon%203.jpg?width=1000",
    nearby: { beaches: ["Ko Olina Lagoons"], trails: ["Lagoon walk"], food: ["Pearlridge/Aiea food"] },
    bestItineraryDays: ["Saturday", "Wednesday"],
    recommendedStop: "Central stop on the way between Ko Olina and Honolulu/Windward.",
    driveFromResort: "22-35 min"
  },
  {
    id: "makeke-waianae",
    name: "Mākeke Waiʻanae: Waianae Farmers Market",
    days: ["Saturday"],
    hours: "8am-12pm",
    location: "Waiʻanae Coast Comprehensive Health Center",
    address: "86-260 Farrington Hwy, Waiʻanae, HI 96792",
    region: "West Side",
    lat: 21.4465,
    lng: -158.184,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Ko%20Olina%20Lagoon%203.jpg?width=1000",
    nearby: { beaches: ["Ko Olina Lagoons", "West side beaches"], trails: ["Lagoon walk"], food: ["Ko Olina restaurants"] },
    bestItineraryDays: ["Saturday", "Wednesday"],
    recommendedStop: "Close-ish west-side alternative if skipping cross-island driving.",
    driveFromResort: "25-35 min"
  },
  {
    id: "waialua",
    name: "Waialua Farmers Market",
    days: ["Saturday"],
    hours: "8:30am-1pm",
    location: "Waialua",
    address: "67-106 Kealohanui St, Waialua, HI 96791",
    region: "North Shore",
    lat: 21.5742,
    lng: -158.1303,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Waimea%20Bay%20Beach%20%2812598985244%29.jpg?width=1000",
    nearby: { beaches: ["Waimea Bay", "Haleʻiwa"], trails: ["Waimea area"], food: ["Giovanni's Shrimp Truck", "Coffee Gallery"] },
    bestItineraryDays: ["Monday"],
    recommendedStop: "Great North Shore alignment if the day moves to Saturday.",
    driveFromResort: "40-55 min"
  },
  {
    id: "village-night-market",
    name: "Village Night Market",
    days: ["Saturday"],
    hours: "5-9pm",
    location: "Central/West Oʻahu night market",
    address: "94-790 Lumiaina St, Waipahu, HI 96797",
    region: "Central",
    lat: 21.403,
    lng: -158.007,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Ko%20Olina%20Lagoon%203.jpg?width=1000",
    nearby: { beaches: ["Ko Olina Lagoons"], trails: ["Lagoon walk"], food: ["Waipahu/Kapolei food"] },
    bestItineraryDays: ["Saturday", "Wednesday"],
    recommendedStop: "Evening option if the family wants a local market without Waikīkī.",
    driveFromResort: "20-30 min"
  },
  {
    id: "mililani",
    name: "Mililani Farmers Market",
    days: ["Sunday"],
    hours: "8-11am",
    location: "Mililani High School",
    address: "95-1200 Meheula Pkwy, Mililani, HI 96789",
    region: "Central",
    lat: 21.475,
    lng: -158.009,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Waimea%20Bay%20Beach%20%2812598985244%29.jpg?width=1000",
    nearby: { beaches: ["North Shore beaches"], trails: ["Waimea area"], food: ["Mililani casual food"] },
    bestItineraryDays: ["Sunday", "Monday"],
    recommendedStop: "Central stop if Sunday timing shifts before Mānoa.",
    driveFromResort: "35-45 min"
  },
  {
    id: "kailua-town-sunday",
    name: "KailuaTown Farmers Market",
    days: ["Sunday"],
    hours: "8am-12pm",
    location: "Kailua Elementary School",
    address: "315 Kuulei Rd, Kailua, HI 96734",
    region: "Windward",
    lat: 21.3971,
    lng: -157.7429,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Kailua%20Beach%20Park%20-%20Oahu%20-%20Hawaii.jpg?width=1000",
    nearby: { beaches: ["Kailua Beach Park", "Lanikai Beach"], trails: ["Judd Trail", "Pali Twin Falls"], food: ["Kalapawai Market"] },
    bestItineraryDays: ["Saturday", "Sunday"],
    recommendedStop: "Excellent Kailua-side pairing if the group swaps beach days.",
    driveFromResort: "55-70 min",
    parkingWarning: "Go early and keep Lanikai as optional."
  },
  {
    id: "aloha-market-waikiki",
    name: "Aloha Market at Waikiki",
    days: ["Sunday"],
    hours: "8am-2pm",
    location: "Waikīkī",
    address: "227 Lewers St, Honolulu, HI 96815",
    region: "Waikiki",
    lat: 21.2792,
    lng: -157.8317,
    photo: marketPhoto,
    nearby: { beaches: ["Waikīkī Beach"], trails: ["Diamond Head area"], food: ["Waikīkī restaurants"] },
    bestItineraryDays: ["Thursday"],
    recommendedStop: "Optional Waikīkī outing; not efficient for Ko Olina recovery days.",
    driveFromResort: "40-65 min",
    parkingWarning: "Waikīkī parking can be slow and costly."
  },
  {
    id: "lokahi-kailua",
    name: "Lōkahi Kailua Market",
    days: ["Sunday"],
    hours: "9am-1pm",
    location: "Kailua town",
    address: "340 Uluniu St, Kailua, HI 96734",
    region: "Windward",
    lat: 21.3945,
    lng: -157.7434,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Kailua%20Beach%20Park%20-%20Oahu%20-%20Hawaii.jpg?width=1000",
    nearby: { beaches: ["Kailua Beach Park", "Lanikai Beach"], trails: ["Judd Trail", "Pali Twin Falls"], food: ["Kalapawai Market"] },
    bestItineraryDays: ["Saturday", "Sunday"],
    recommendedStop: "Good Kailua-side Sunday option with beach nearby.",
    driveFromResort: "55-70 min"
  },
  {
    id: "market-on-the-ranch",
    name: "Market on the Ranch",
    days: ["Sunday"],
    hours: "11am-3pm",
    location: "Turtle Bay / Kahuku area",
    address: "57-091 Kamehameha Hwy, Kahuku, HI 96731",
    region: "North Shore",
    lat: 21.7034,
    lng: -157.9974,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Waimea%20Bay%20Beach%20%2812598985244%29.jpg?width=1000",
    nearby: { beaches: ["Sunset Beach", "Waimea Bay"], trails: ["Waimea area"], food: ["North Shore food trucks"] },
    bestItineraryDays: ["Monday"],
    recommendedStop: "North Shore fit only if the North Shore day moves to Sunday.",
    driveFromResort: "65-85 min",
    parkingWarning: "Longer return drive; leave before late afternoon if possible."
  }
];

export const routePlans: RoutePlan[] = [
  {
    dayId: "fri-arrival",
    label: "Day 1 — Arrival",
    color: "#2f80ed",
    leaveBy: "After landing; leave airport before afternoon traffic if bags arrive quickly.",
    totalDrive: "45-75 min including Costco",
    trafficNote: "H-1 westbound can build in late afternoon; keep the day simple.",
    parkingWarnings: ["Airport rental car timing", "Costco lot can be busy on Fridays"],
    scenicPins: ["Ko Olina sunset walk"],
    stops: ["resort", "costco", "makana-ka-makana", "mini-artfest-marriott", "ko-olina-golf-club"]
  },
  {
    dayId: "sat-lanikai",
    label: "Day 2 — Lanikai (Best Day)",
    color: "#f59e0b",
    leaveBy: "5:45–6:00 AM",
    totalDrive: "2-2.5 hr round trip",
    trafficNote: "Leave before 6 AM to beat cross-island traffic. Return before midday traffic builds.",
    parkingWarnings: ["Lanikai street parking fills before 8:30 AM — arrive no later", "No overflow parking available"],
    scenicPins: ["Ko'olau ridge views from Kalawahine", "Mokulua Islands from Lanikai"],
    stops: ["resort", "kalawahine", "lanikai", "kalapawai", "tropical-farms-stop", "mano-chocolate", "royal-hawaiian-golf-club"]
  },
  {
    dayId: "sun-waimanalo",
    label: "Day 3 — Waimanalo + Market",
    color: "#3f7f5f",
    leaveBy: "7:00 AM",
    totalDrive: "2.5-3 hr loop",
    trafficNote: "Cross-island early. Return through Honolulu before late-afternoon commute.",
    parkingWarnings: ["Judd Trail: street parking only", "Kailua market: arrive by 9 AM"],
    scenicPins: ["Kailua bay views", "Waimanalo coastline"],
    stops: ["resort", "judd", "kailua-town-sunday", "mon-cha-cha-tea-kailua", "waimanalo", "fresh-catch", "ono-seafood-poke", "bayview-night-market"]
  },
  {
    dayId: "mon-memorial",
    label: "Day 4 — Memorial Day Route",
    color: "#8d5cf6",
    leaveBy: "6:45 AM",
    totalDrive: "2.5-3 hr loop",
    trafficNote: "Avoid North Shore on Memorial Day — this east-side coastal route stays significantly calmer.",
    parkingWarnings: ["Lulumahu: limited roadside, confirm permit", "Halona: small lot, arrive before 9:30 AM"],
    scenicPins: ["Halona Blowhole coastal view", "Sandy Beach lookout"],
    stops: ["resort", "lulumahu", "halona", "sandy", "adelas", "fresh-catch", "kaiser-ptsa"]
  },
  {
    dayId: "tue-waimea",
    label: "Day 5 — Waimea Bay (Early)",
    color: "#f26b5e",
    leaveBy: "6:15 AM — critical for parking",
    totalDrive: "2-2.5 hr round trip",
    trafficNote: "H-2 North is fast early morning. Return south before noon lunch traffic.",
    parkingWarnings: ["Waimea Bay lot fills by 7:30–8:00 AM — no exceptions", "No overflow parking on Tuesdays"],
    scenicPins: ["Waimea Bay cliff views", "Haleʻiwa harbor"],
    stops: ["resort", "waimea-bay", "sharks-cove", "giovannis", "coffee-gallery", "dole-plantation", "waialua", "green-world-coffee", "turtle-bay-golf-course"]
  },
  {
    dayId: "wed-kualoa",
    label: "Day 6 — Kualoa Scenic",
    color: "#2aa7a5",
    leaveBy: "7:00 AM",
    totalDrive: "2.5-3 hr loop plus evening market",
    trafficNote: "Windward morning drive is smooth. Evening return from Blaisdell via H-1 — allow extra time.",
    parkingWarnings: ["Crouching Lion: roadside only", "Blaisdell market: street/lot parking"],
    scenicPins: ["Ko'olau mountain views at Kualoa", "Chinaman's Hat island", "Kahana Bay from Crouching Lion"],
    stops: ["resort", "crouching-lion", "kualoa", "tropical-farms-stop", "honolulu-farmers", "mon-cha-cha-tea-honolulu", "windward-mall", "aloha-stadium"]
  },
  {
    dayId: "thu-resort",
    label: "Day 7 — Resort Day",
    color: "#d9a441",
    leaveBy: "Late morning only if doing an optional outing.",
    totalDrive: "0-1 hr optional",
    trafficNote: "Stay close to Ko Olina. One short optional outing max.",
    parkingWarnings: ["Keep the day simple — no city driving"],
    scenicPins: ["Ko Olina sunset", "Lagoon walk"],
    stops: ["resort", "makana-ka-makana", "mini-artfest-marriott", "ko-hana-rum", "ko-olina-golf-club", "royal-kunia-country-club"]
  },
  {
    dayId: "fri-departure",
    label: "Day 8 — Departure",
    color: "#64748b",
    leaveBy: "Leave Ko Olina 2.5-3 hours before flight time.",
    totalDrive: "25-45 min to HNL plus rental return",
    trafficNote: "Keep this route simple: resort, final lagoon walk, airport.",
    parkingWarnings: ["Avoid adding any outing", "Build time for rental car return"],
    scenicPins: ["Final Ko Olina lagoon walk"],
    stops: ["resort", "mini-artfest-marriott"]
  }
];

export const adHocFarmersMarkets = [
  "Aloha Home Market",
  "Aloun Country Market",
  "Art+Flea Hawaii's Favorite Urban Market",
  "DoHo Night Market",
  "Farmers Market at Hoʻopili Community Association",
  "Hana Hou Makeke: Vintage Hawaiian Market",
  "Harbors Vintage Vintage Market",
  "Hawaiʻi's Shop Local Pop-up",
  "Honolulu Makers Market",
  "Honolulu Night Market",
  "Hoʻomau Market",
  "Kaimukī Night Market",
  "Kaiāulu Market",
  "Keiki Makers Market",
  "Koʻolau Night Market",
  "Kaiwiʻula Night Market",
  "Māʻona Market",
  "Mākia Market",
  "Mālama Hawaiʻi Makers Market",
  "Maunawili Night Market",
  "New Wave Night Market",
  "Night Market Central at Pearl at Kalauao",
  "Sunshine People Market",
  "Taste of Aloha Night Market",
  "Taste of Makaha Night Market",
  "The Blessed Friday Market",
  "The Mom Made Market Hawaii",
  "Vintage Night Market at Koko Marina Center",
  "What the Truck?! at Waikele"
];

const oahuScenicPhoto = "https://commons.wikimedia.org/wiki/Special:FilePath/Aerial%20view%20of%20Disneys%20Aulani%20resort%20and%20Ko%20Olina%20Lagoon.jpg?width=1000";
const northShorePhoto = "https://commons.wikimedia.org/wiki/Special:FilePath/Waimea%20Bay%20Beach%20%2812598985244%29.jpg?width=1000";
const windwardPhoto = "https://commons.wikimedia.org/wiki/Special:FilePath/Kailua%20Beach%20Park%20-%20Oahu%20-%20Hawaii.jpg?width=1000";

export const madeInHawaiiLocations: MadeInHawaiiLocation[] = [
  {
    id: "dole-plantation",
    name: "Dole Plantation",
    category: "pineapple",
    address: "64-1550 Kamehameha Hwy, Wahiawā, HI 96786",
    region: "Central Oʻahu",
    lat: 21.525,
    lng: -158.037,
    photoGallery: [northShorePhoto, oahuScenicPhoto],
    onsiteProduction: true,
    familyFriendly: true,
    tasting: "Pineapple treats and Dole Whip-style snacks",
    duration: "30-75 min",
    itineraryCompatibility: ["Sunday Dole + Aihualama", "North Shore day"],
    scenicValue: 4,
    notes: "Best as a quick agriculture-themed stop rather than a full-day tourist attraction.",
    mapQuery: "Dole Plantation Oahu"
  },
  {
    id: "green-world-coffee",
    name: "Green World Coffee Farm",
    category: "coffee",
    address: "71-101 Kamehameha Hwy, Wahiawā, HI 96786",
    region: "Central Oʻahu",
    lat: 21.538,
    lng: -158.035,
    photoGallery: [northShorePhoto, oahuScenicPhoto],
    onsiteProduction: true,
    familyFriendly: true,
    tasting: "Coffee samples; onsite roasting/coffee farm experience",
    duration: "20-45 min",
    itineraryCompatibility: ["North Shore day", "Dole quick stop"],
    scenicValue: 4,
    notes: "Ranks high because it is local, quick, and fits the Ko Olina-to-North-Shore route.",
    mapQuery: "Green World Coffee Farm Wahiawa"
  },
  {
    id: "mano-chocolate",
    name: "Mānoa Chocolate",
    category: "cacao",
    address: "315 Uluniu St, Kailua, HI 96734",
    region: "Windward",
    lat: 21.394,
    lng: -157.743,
    photoGallery: [windwardPhoto, oahuScenicPhoto],
    onsiteProduction: true,
    familyFriendly: true,
    tasting: "Chocolate tasting and factory-style experience",
    duration: "30-75 min",
    itineraryCompatibility: ["Saturday Kailua side", "Tuesday beach day"],
    scenicValue: 4,
    notes: "Excellent local-production experience: cacao/chocolate in Kailua.",
    mapQuery: "Manoa Chocolate Kailua"
  },
  {
    id: "aloha-beer-production",
    name: "Aloha Beer Company",
    category: "brewery",
    address: "700 Queen St, Honolulu, HI 96813",
    region: "Kakaʻako / Honolulu",
    lat: 21.3012,
    lng: -157.8585,
    photoGallery: [oahuScenicPhoto],
    onsiteProduction: true,
    familyFriendly: true,
    tasting: "Local brewery taproom; verify current onsite brewing/tour availability",
    duration: "45-90 min",
    itineraryCompatibility: ["Tuesday optional brewery", "Thursday local food day"],
    scenicValue: 3,
    notes: "Included because it is a local brewery/taproom, not a generic bar.",
    mapQuery: "Aloha Beer Company Honolulu"
  },
  {
    id: "honolulu-beerworks",
    name: "Honolulu Beerworks",
    category: "brewery",
    address: "328 Cooke St, Honolulu, HI 96813",
    region: "Kakaʻako / Honolulu",
    lat: 21.2981,
    lng: -157.858,
    photoGallery: [oahuScenicPhoto],
    onsiteProduction: true,
    familyFriendly: true,
    tasting: "Local craft brewery taproom",
    duration: "45-90 min",
    itineraryCompatibility: ["Thursday local food day"],
    scenicValue: 3,
    notes: "Authentic brewery option for adults while staying food/local-production focused.",
    mapQuery: "Honolulu Beerworks"
  },
  {
    id: "ko-hana-rum",
    name: "Kō Hana Distillers",
    category: "distillery",
    address: "92-1770 Kunia Rd #227, Kunia Camp, HI 96759",
    region: "Central / West Side",
    lat: 21.456,
    lng: -158.064,
    photoGallery: [oahuScenicPhoto],
    onsiteProduction: true,
    familyFriendly: true,
    tasting: "Rum tasting for adults; sugarcane/agricultural production story",
    duration: "45-90 min",
    itineraryCompatibility: ["Wednesday flexible day", "Thursday resort day"],
    scenicValue: 4,
    notes: "Strong fit: local agricultural production, west-side convenience, and authentic Hawaii-made story.",
    mapQuery: "Ko Hana Distillers Kunia"
  },
  {
    id: "ululani-production",
    name: "Ululani's Hawaiian Shave Ice",
    category: "shave-ice",
    address: "Oʻahu location varies by route",
    region: "Route-dependent",
    lat: 21.3932,
    lng: -157.7435,
    photoGallery: [windwardPhoto],
    onsiteProduction: true,
    familyFriendly: true,
    tasting: "Shave ice",
    duration: "15-30 min",
    itineraryCompatibility: ["Saturday Kailua side", "North Shore day"],
    scenicValue: 3,
    notes: "Family dessert stop; keep this as the default shave ice brand throughout the planner.",
    mapQuery: "Ululani's Hawaiian Shave Ice Oahu"
  },
  {
    id: "ono-seafood-poke",
    name: "Ono Seafood",
    category: "poke",
    address: "747 Kapahulu Ave, Honolulu, HI 96816",
    region: "Honolulu",
    lat: 21.2806,
    lng: -157.8137,
    photoGallery: [windwardPhoto],
    onsiteProduction: true,
    familyFriendly: true,
    tasting: "Fresh poke bowls",
    duration: "20-40 min",
    itineraryCompatibility: ["Sunday Mānoa/Waimānalo"],
    scenicValue: 2,
    notes: "Local food production experience that pairs well with the Mānoa/Waimānalo route.",
    mapQuery: "Ono Seafood Honolulu"
  },
  {
    id: "giovannis-shrimp",
    name: "Giovanni's Shrimp Truck",
    category: "shrimp",
    address: "66-472 Kamehameha Hwy, Haleʻiwa, HI 96712",
    region: "North Shore",
    lat: 21.5931,
    lng: -158.1037,
    photoGallery: [northShorePhoto],
    onsiteProduction: true,
    familyFriendly: true,
    tasting: "Garlic shrimp plates",
    duration: "30-60 min",
    itineraryCompatibility: ["North Shore day"],
    scenicValue: 4,
    notes: "Scenic roadside food destination with strong North Shore route fit.",
    mapQuery: "Giovanni's Shrimp Truck Haleiwa"
  },
  {
    id: "tropical-farms",
    name: "Tropical Farms Macadamia Nuts",
    category: "macadamia",
    address: "49-227 Kamehameha Hwy, Kāneʻohe, HI 96744",
    region: "Windward",
    lat: 21.511,
    lng: -157.845,
    photoGallery: [windwardPhoto],
    onsiteProduction: true,
    familyFriendly: true,
    tasting: "Macadamia nut samples and local snacks",
    duration: "20-45 min",
    itineraryCompatibility: ["Saturday Kailua side", "Wednesday flexible adventure"],
    scenicValue: 4,
    notes: "Good local snack/agriculture stop if the route passes Kāneʻohe.",
    mapQuery: "Tropical Farms Macadamia Nuts Kaneohe"
  }
];

export const golfCourses: GolfCourse[] = [
  {
    id: "ko-olina-golf-club",
    name: "Ko Olina Golf Club",
    website: "https://www.koolinagolf.com/tee-times-and-rates/",
    address: "92-1220 Aliinui Dr, Kapolei, HI 96707",
    lat: 21.337,
    lng: -158.123,
    access: "Resort/Public",
    driveFromKoOlina: "3-8 min",
    price18: "Approx. $275 visitor / resort rates vary dynamically",
    price9: "Approx. $140 9 holes",
    twilight: "Approx. $210 after 1 PM; current site notes dynamic rates",
    rentalClubs: "Available; verify when booking",
    drivingRange: "Excellent practice facilities and warm-up basket noted by course",
    difficulty: "Intermediate",
    scenicRating: 5,
    beginnerRating: 4,
    familyRating: 5,
    duration: "9 holes 2-2.5 hr; 18 holes about 4 hr 20 min",
    bestTeeTime: "Early morning for cooler weather or later 9-hole window for a resort day",
    weatherWindNote: "Leeward side is usually drier; afternoon trade winds can still matter.",
    itineraryCompatibility: ["Wednesday flexible day", "Thursday resort day", "Departure morning if timing allows"],
    tags: ["Near Ko Olina", "Resort Luxury", "Practice Facilities", "Rental Clubs", "Most Convenient Option"],
    recommendationLabels: ["Closest to resort", "Best quick round", "Best logistics", "Most Convenient Option"],
    photo: oahuScenicPhoto,
    notes: "Most convenient option for this trip and easiest to fit around family resort time.",
    pricingUpdated: "Estimate checked May 2026; rates are dynamically updateable."
  },
  {
    id: "turtle-bay-golf-course",
    name: "Turtle Bay Golf",
    website: "https://www.turtlebayexperiences.com/things-to-do/golf",
    address: "57-091 Kamehameha Hwy, Kahuku, HI 96731",
    lat: 21.7034,
    lng: -157.9974,
    access: "Resort/Public",
    driveFromKoOlina: "65-85 min",
    price18: "Approx. $285 visitor / guest rates may start lower",
    price9: "Approx. $150 for 9 holes; guest rates may vary",
    twilight: "Check booking engine for current late-day pricing",
    rentalClubs: "Available; verify when booking",
    drivingRange: "Practice facilities available",
    difficulty: "Challenging",
    scenicRating: 5,
    beginnerRating: 3,
    familyRating: 4,
    duration: "9 holes 2-2.5 hr; 18 holes 4.5 hr",
    bestTeeTime: "Pair with North Shore day; early tee time or a planned separate golf morning",
    weatherWindNote: "North Shore wind can add challenge; surf-season traffic can slow return.",
    itineraryCompatibility: ["Monday North Shore day"],
    tags: ["Ocean Views", "Resort Luxury", "Challenging", "North Shore", "Rental Clubs"],
    recommendationLabels: ["Best ocean views", "Best scenic course", "Best for serious golfers"],
    photo: northShorePhoto,
    notes: "Arnold Palmer course feel with North Shore scenery and a luxury golf experience.",
    pricingUpdated: "Estimate checked May 2026; verify direct booking."
  },
  {
    id: "royal-hawaiian-golf-club",
    name: "Royal Hawaiian Golf Club",
    website: "https://www.royalhawaiiangc.com/",
    address: "770 Auloa Rd, Kailua, HI 96734",
    lat: 21.375,
    lng: -157.778,
    access: "Public",
    driveFromKoOlina: "55-75 min",
    price18: "Approx. $200 visitor rate",
    twilight: "Check direct booking for current late-day rates",
    rentalClubs: "Available; verify when booking",
    drivingRange: "Limited practice/warmup; verify current facilities",
    difficulty: "Challenging",
    scenicRating: 5,
    beginnerRating: 2,
    familyRating: 3,
    duration: "18 holes 4.5-5 hr",
    bestTeeTime: "Early morning on a Windward/Kailua side day",
    weatherWindNote: "Lush valley can be wet; check rain before committing.",
    itineraryCompatibility: ["Saturday Kailua side", "Tuesday Windward beach day"],
    tags: ["Jungle Course", "Mountain Views", "Challenging", "Scenic"],
    recommendationLabels: ["Best jungle experience", "Most visually unique", "Best mountain scenery"],
    photo: windwardPhoto,
    notes: "Dramatic Koʻolau/Jurassic-style setting; amazing visually, but not the easiest family round.",
    pricingUpdated: "Estimate checked May 2026; verify direct booking."
  },
  {
    id: "royal-kunia-country-club",
    name: "Royal Kunia Country Club, Inc.",
    website: "https://www.royalkuniacc.com/",
    address: "94-1509 Anonui St, Waipahu, HI 96797",
    lat: 21.393,
    lng: -158.032,
    access: "Public",
    driveFromKoOlina: "20-30 min",
    price18: "Varies; generally mid-island public-course pricing",
    twilight: "Check booking engine",
    rentalClubs: "Verify when booking",
    drivingRange: "Practice facilities; verify current availability",
    difficulty: "Intermediate",
    scenicRating: 4,
    beginnerRating: 4,
    familyRating: 4,
    duration: "18 holes about 4-4.5 hr",
    bestTeeTime: "Morning or twilight on a flexible/resort day",
    weatherWindNote: "Central ridge views; afternoon winds can pick up.",
    itineraryCompatibility: ["Wednesday flexible day", "Thursday resort day"],
    tags: ["Mountain Views", "Near Ko Olina", "Local Favorite", "Intermediate"],
    recommendationLabels: ["Best value near resort", "Best relaxed family round"],
    photo: oahuScenicPhoto,
    notes: "Good mid-island option with scenic elevation views and easier logistics than Windward/North Shore.",
    pricingUpdated: "Seasonal estimate; verify direct booking."
  },
  {
    id: "olomana-golf-links",
    name: "Olomana Golf Links",
    website: "https://olomanalinks.com/",
    address: "41-1801 Kalanianaʻole Hwy, Waimānalo, HI 96795",
    lat: 21.341,
    lng: -157.724,
    access: "Public",
    driveFromKoOlina: "60-80 min",
    price18: "Check current rates; course site notes operational changes",
    twilight: "Check current booking",
    rentalClubs: "Rental clubs listed at about $30 per set",
    drivingRange: "Driving range noted, but current site also flags closures; verify before going",
    difficulty: "Beginner-friendly",
    scenicRating: 4,
    beginnerRating: 5,
    familyRating: 4,
    duration: "9-hole/practice style 1-2.5 hr; full round 4 hr if available",
    bestTeeTime: "Windward beach day add-on only if currently open",
    weatherWindNote: "Windward showers possible; check same-day course status.",
    itineraryCompatibility: ["Tuesday Windward beach day", "Saturday Kailua side"],
    tags: ["Beginner Friendly", "Mountain Views", "Driving Range", "Local Favorite"],
    recommendationLabels: ["Best relaxed family round", "Best practice option"],
    photo: windwardPhoto,
    notes: "More casual/local feel and good for lower-pressure golf, but verify current open status.",
    pricingUpdated: "Course site checked May 2026; verify before planning."
  },
  {
    id: "kaneohe-klipper",
    name: "Kaneohe Klipper Golf Course",
    website: "https://hawaii.usmc-mccs.org/recreation-fitness/golf",
    address: "Kaneohe Bay Dr, MCBH, Kāneʻohe, HI 96734",
    lat: 21.449,
    lng: -157.761,
    access: "Military-affiliated",
    driveFromKoOlina: "55-75 min",
    price18: "Military/MCCS rates vary by eligibility",
    price9: "9-hole rates available for eligible players",
    twilight: "Twilight/sunset categories listed by MCCS",
    rentalClubs: "Verify with MCCS",
    drivingRange: "Practice facilities; verify access",
    difficulty: "Intermediate",
    scenicRating: 5,
    beginnerRating: 3,
    familyRating: 3,
    duration: "9 holes 2 hr; 18 holes 4-4.5 hr",
    bestTeeTime: "Only if access is confirmed; pair with Windward day",
    weatherWindNote: "Ocean wind and base access logistics are the key variables.",
    itineraryCompatibility: ["Saturday Kailua side", "Tuesday Windward beach day"],
    tags: ["Ocean Views", "Military-affiliated", "Challenging", "Windward"],
    recommendationLabels: ["Best ocean views if accessible"],
    photo: windwardPhoto,
    notes: "Incredible ocean-view course, but access is military-affiliated and must be confirmed.",
    pricingUpdated: "MCCS rate sheet checked May 2026; eligibility-dependent."
  },
  {
    id: "ala-wai-golf-course",
    name: "Ala Wai Golf Course",
    website: "https://alawairange.com/rates",
    address: "404 Kapahulu Ave, Honolulu, HI 96815",
    lat: 21.282,
    lng: -157.819,
    access: "Municipal",
    driveFromKoOlina: "40-65 min",
    price18: "Municipal rates; check official rate page",
    twilight: "Check official rate page",
    rentalClubs: "Verify with course/range",
    drivingRange: "Driving range available",
    difficulty: "Beginner-friendly",
    scenicRating: 3,
    beginnerRating: 5,
    familyRating: 4,
    duration: "Fast round possible depending on tee sheet",
    bestTeeTime: "Only if already going into Honolulu; keep the pairing local-food focused",
    weatherWindNote: "Urban course; less wind exposure than coastal courses.",
    itineraryCompatibility: ["Thursday local food day"],
    tags: ["More Affordable", "Beginner Friendly", "Driving Range", "Fast Round"],
    recommendationLabels: ["Best affordable/casual option"],
    photo: oahuScenicPhoto,
    notes: "Affordable/casual option, but lower priority because it pulls the trip into town.",
    pricingUpdated: "Verify official municipal rates."
  },
  {
    id: "mililani-golf-club",
    name: "Mililani Golf Club",
    website: "https://mililanigolf.com/rates/",
    address: "95-176 Kuahelani Ave, Mililani, HI 96789",
    lat: 21.452,
    lng: -158.01,
    access: "Public",
    driveFromKoOlina: "35-45 min",
    price18: "Approx. $63-$73 public club play shown on course rate page",
    twilight: "Check direct booking",
    rentalClubs: "Verify when booking",
    drivingRange: "Practice facilities; verify current availability",
    difficulty: "Beginner-friendly",
    scenicRating: 3,
    beginnerRating: 5,
    familyRating: 4,
    duration: "18 holes 4 hr; quicker windows may be available",
    bestTeeTime: "Morning or twilight on a flexible day",
    weatherWindNote: "Central location; usually straightforward weather compared with windward valley courses.",
    itineraryCompatibility: ["Wednesday flexible day", "North Shore transit"],
    tags: ["More Affordable", "Beginner Friendly", "Local Favorite"],
    recommendationLabels: ["Best value", "Best relaxed family round"],
    photo: northShorePhoto,
    notes: "Good affordable/casual option with central route compatibility.",
    pricingUpdated: "Rate page checked May 2026; verify direct booking."
  },
  {
    id: "moanalua-golf-club",
    name: "Moanalua Golf Club",
    website: "https://www.moanaluagolfclub.com/",
    address: "1250 Ala Aolani St, Honolulu, HI 96819",
    lat: 21.356,
    lng: -157.894,
    access: "Semi-private",
    driveFromKoOlina: "25-40 min",
    price18: "Check direct booking",
    twilight: "Check direct booking",
    rentalClubs: "Verify when booking",
    drivingRange: "Verify current facilities",
    difficulty: "Beginner-friendly",
    scenicRating: 3,
    beginnerRating: 4,
    familyRating: 4,
    duration: "Shorter/casual round possible",
    bestTeeTime: "Flexible day or airport-side timing",
    weatherWindNote: "Central/Honolulu valley weather; check rain.",
    itineraryCompatibility: ["Arrival/departure timing", "Wednesday flexible day"],
    tags: ["More Affordable", "Fast Round", "Local Favorite"],
    recommendationLabels: ["Best quick round", "Best casual option"],
    photo: oahuScenicPhoto,
    notes: "Casual option for golfers who want lower-pressure logistics than resort courses.",
    pricingUpdated: "Verify direct booking."
  }
];

export const activityFilters = [
  "Easy",
  "Teen friendly",
  "Waterfall",
  "Beach",
  "Low crowds",
  "Early morning",
  "Relaxing",
  "Adventure",
  "Scenic"
];

export const sampleComments: TripComment[] = [
  {
    id: "c1",
    itemId: "sat-lanikai",
    author: "Aunt Lisa",
    text: "5:45 AM is early but I am IN for Lanikai on the best beach day. Parking drama is worth it for that water.",
    reaction: "🌊",
    interest: "must-do",
    createdAt: new Date("2026-05-01T10:00:00").toISOString()
  },
  {
    id: "c2",
    itemId: "tue-waimea",
    author: "Maya",
    text: "Smart move putting Waimea on Tuesday instead of Memorial Day. Giovanni's shrimp truck is non-negotiable.",
    reaction: "🍧",
    interest: "must-do",
    createdAt: new Date("2026-05-02T12:00:00").toISOString()
  },
  {
    id: "c3",
    itemId: "mon-memorial",
    author: "Dad",
    text: "Early start is fine if coffee is acquired within the first hour. Halona Cove sounds incredible.",
    reaction: "☕",
    interest: "interested",
    createdAt: new Date("2026-05-03T08:30:00").toISOString()
  }
];

export const sampleSuggestions: Suggestion[] = [];

export const packingItems = [
  "Reef shoes",
  "Beach towels",
  "Hiking shoes",
  "Snorkel gear",
  "Phone chargers",
  "Reef-safe sunscreen",
  "Water bottles",
  "Hats",
  "Light rain jacket",
  "Dry bag"
];
