import type { Beach, FarmerMarket, GolfCourse, ItineraryDay, MadeInHawaiiLocation, Place, RoutePlan, Suggestion, Trail, TripComment } from "@/lib/types";

export const tripStart = process.env.NEXT_PUBLIC_TRIP_START ?? "2026-05-22T00:00:00-10:00";

export const resort = {
  name: "Marriott's Ko Olina Beach Club",
  address: "92-161 Waipahe Place, Kapolei, HI 96707",
  checkIn: "May 22",
  checkOut: "May 29",
  note: "Most breakfasts will be at the resort before heading out for activities."
};

export const days: ItineraryDay[] = [
  {
    id: "fri-arrival",
    date: "Friday, May 22",
    title: "Arrival + Resort Relaxation",
    theme: "Land softly, stock up, and let the resort do the work.",
    wakeUp: "Travel day: keep it gentle after landing.",
    hero: "https://commons.wikimedia.org/wiki/Special:FilePath/Ko%20Olina%20Sunset.jpg?width=1600",
    difficulty: "Flexible",
    walking: "0.5-1.5 miles",
    teenFriendly: true,
    noPermit: true,
    driveTime: "HNL to resort: 25-40 min without traffic",
    parking: "Use Costco first, then resort valet/self-parking after check-in.",
    crowdTip: "Avoid adding a second destination after arrival; save energy for the week.",
    trail: "Sunset lagoon walk",
    beach: "Ko Olina lagoon",
    food: ["Costco provisions", "Monkeypod Kitchen", "Longboards Bar & Grill"],
    optional: ["Pool time", "Beach chairs", "Sunset photos", "Casual dinner"],
    tags: ["Relaxing", "Low crowds", "Scenic"],
    schedule: [
      { time: "12:10 PM", plan: "Airport arrival, rental car pickup, and luggage load." },
      { time: "Afternoon", plan: "Costco stop for snacks, waters, reef-safe sunscreen, and breakfast basics." },
      { time: "Check-in", plan: "Settle into Marriott's Ko Olina Beach Club." },
      { time: "Sunset", plan: "Relax at the resort beach or pool, then take a lagoon walk." }
    ]
  },
  {
    id: "sat-kailua",
    date: "Saturday, May 23",
    title: "Windward Waterfalls + Kailua",
    theme: "Short green trail, bright beach water, and legendary pancakes.",
    wakeUp: "Leave by 6:45 AM for cooler trail time and easier Kailua parking.",
    hero: "https://commons.wikimedia.org/wiki/Special:FilePath/Kailua%20Beach%20Park%20-%20Oahu%20-%20Hawaii.jpg?width=1600",
    difficulty: "Easy-Moderate",
    walking: "1-2.5 miles",
    teenFriendly: true,
    noPermit: true,
    driveTime: "Ko Olina to Kailua side: 50-70 min",
    parking: "Lanikai parking is tight; Kailua Beach Park is easier and calmer logistically.",
    crowdTip: "Hit the beach before late morning and keep Lanikai as a photo stop if crowded.",
    trail: "Judd Trail OR Pali Twin Falls",
    beach: "Lanikai Beach OR Kailua Beach",
    food: ["Boots & Kimo's", "Kalapawai Market"],
    optional: ["Ululani's Hawaiian Shave Ice", "Kailua Farmers Market"],
    tags: ["Easy", "Waterfall", "Beach", "Teen friendly", "Early morning", "Scenic"],
    schedule: [
      { time: "6:45 AM", plan: "Depart after an easy resort breakfast." },
      { time: "8:00 AM", plan: "Choose Judd Trail or Pali Twin Falls depending on weather and trail conditions." },
      { time: "10:15 AM", plan: "Beach time at Kailua or Lanikai." },
      { time: "Lunch", plan: "Boots & Kimo's or Kalapawai Market." },
      { time: "Afternoon", plan: "Ululani's Hawaiian Shave Ice and optional farmers market before returning west." }
    ]
  },
  {
    id: "sun-manoa",
    date: "Sunday, May 24",
    title: "Dole + Aihualama + Waimānalo",
    theme: "Quick pineapple stop, jungle scenery, town lunch, and a spacious beach.",
    wakeUp: "Leave around 7:00 AM to keep the trail cool.",
    hero: "https://commons.wikimedia.org/wiki/Special:FilePath/Waimanalo%20Beach%20%2827829441405%29.jpg?width=1600",
    difficulty: "Easy-Moderate",
    walking: "Up to 2.8 miles if doing a partial route",
    teenFriendly: true,
    noPermit: true,
    driveTime: "Ko Olina to Dole: 25-35 min; Dole to Mānoa: 35-50 min; Mānoa to Waimānalo: 35-45 min",
    parking: "Use legal neighborhood or paid lot options; keep valuables out of sight.",
    crowdTip: "Partial Mānoa keeps the day flexible if mud or rain slows everyone down.",
    trail: "Aihualama Trail / partial Mānoa",
    beach: "Waimānalo Beach",
    food: ["Ono Seafood", "Fresh Catch"],
    optional: ["Dole Plantation quick stop", "Nuʻuanu Pali Lookout", "Coffee stop in Honolulu"],
    tags: ["Waterfall", "Beach", "Relaxing", "Teen friendly", "Scenic"],
    schedule: [
      { time: "7:00 AM", plan: "Depart Ko Olina with water and trail shoes." },
      { time: "7:35 AM", plan: "Quick Dole Plantation stop if the group wants pineapple or photos." },
      { time: "9:00 AM", plan: "Aihualama Trail / partial Mānoa route." },
      { time: "11:00 AM", plan: "Ono Seafood or Fresh Catch lunch pickup." },
      { time: "12:30 PM", plan: "Waimānalo beach time, then an easy drive back." }
    ]
  },
  {
    id: "mon-north-shore",
    date: "Monday, May 25",
    title: "North Shore Classic Loop",
    theme: "Waimea, Haleʻiwa, Shark's Cove, and Ululani's shave ice.",
    wakeUp: "Leave by 7:00 AM to beat beach and parking pressure.",
    hero: "https://commons.wikimedia.org/wiki/Special:FilePath/Waimea%20Bay%20Oahu%20Hawaii%20Photo%20D%20Ramey%20Logan.jpg?width=1600",
    difficulty: "Easy",
    walking: "1-2 miles, mostly optional",
    teenFriendly: true,
    noPermit: true,
    driveTime: "Ko Olina to Haleʻiwa: 35-50 min; full loop depends on stops",
    parking: "Waimea Bay fills quickly; have Waimea Valley or Haleʻiwa as backup first stops.",
    crowdTip: "Pick two anchor stops instead of trying to force every North Shore highlight.",
    trail: "Waimea Valley walk",
    beach: "Waimea Bay, Shark's Cove, Sunset Beach",
    food: ["Giovanni's Shrimp Truck", "Seven Brothers", "North Shore Tacos", "Ululani's Hawaiian Shave Ice", "Coffee Gallery"],
    optional: ["Short Waimea Valley walk only if the family wants it", "Haleʻiwa local food stops"],
    tags: ["Beach", "Teen friendly", "Scenic", "Adventure", "Shaved ice"],
    schedule: [
      { time: "7:00 AM", plan: "Depart after resort breakfast." },
      { time: "8:00 AM", plan: "Waimea Bay or Waimea Valley depending on parking and weather." },
      { time: "Late morning", plan: "Shark's Cove look/snorkel only if conditions are safe." },
      { time: "Lunch", plan: "Giovanni's, Seven Brothers, or North Shore Tacos, then Ululani's Hawaiian Shave Ice." },
      { time: "Afternoon", plan: "Sunset Beach look, optional Turtle Bay golf, then return." }
    ]
  },
  {
    id: "tue-lulumahu-review",
    date: "Tuesday, May 26",
    title: "Jungle Falls Candidate + Beach",
    theme: "Keep the waterfall feel, but flag permit logistics before committing.",
    wakeUp: "Leave by 6:45 AM if choosing a legal, low-stress jungle option.",
    hero: "https://commons.wikimedia.org/wiki/Special:FilePath/Lanikai%20Beach.jpg?width=1600",
    difficulty: "Easy-Moderate",
    walking: "Target under 3 miles total",
    teenFriendly: true,
    noPermit: false,
    driveTime: "Ko Olina to Nuʻuanu/Mānoa side: 35-55 min; beach add-on 30-45 min",
    parking: "Lulumahu has permit and access logistics; use a no-permit fallback unless the family intentionally books it.",
    crowdTip: "Choose the simplest legal trail early, then shift to beach before heat and traffic.",
    trail: "Lulumahu Falls candidate requires permit; no-permit fallback: Judd Trail/Pali Twin Falls if conditions fit",
    beach: "Kailua Beach Park OR Waimānalo Beach",
    food: ["Adela's Country Eatery", "Fresh Catch"],
    optional: ["Aloha Beer Company", "Ko Olina lagoons", "Sunset swim"],
    tags: ["Waterfall", "Beach", "Early morning", "Scenic", "Teen friendly"],
    schedule: [
      { time: "6:45 AM", plan: "Depart with water, trail shoes, and a legal trail decision." },
      { time: "8:00 AM", plan: "Waterfall/jungle hike candidate. Lulumahu requires a permit, so confirm before choosing it." },
      { time: "11:00 AM", plan: "Adela's Country Eatery or Fresh Catch." },
      { time: "12:30 PM", plan: "Kailua or Waimānalo beach time, then optional Aloha Beer Company." }
    ]
  },
  {
    id: "wed-flex",
    date: "Wednesday, May 27",
    title: "Flexible Chill Day",
    theme: "Low-friction day with room for family favorites.",
    wakeUp: "Sleep in unless the family votes for a sunrise walk.",
    hero: "https://commons.wikimedia.org/wiki/Special:FilePath/Ko%20Olina%20Lagoon%203.jpg?width=1600",
    difficulty: "Flexible",
    walking: "Family choice",
    teenFriendly: true,
    noPermit: true,
    driveTime: "Keep driving under 30 minutes if possible.",
    parking: "Choose easy resort or nearby Kapolei options.",
    crowdTip: "Use the suggestion votes to pick one simple outing, then stop.",
    trail: "Optional short trail",
    beach: "Resort beach or nearby lagoon",
    food: ["Monkeypod Kitchen", "Eggs 'n Things", "Family vote", "Sunset dinner/drinks"],
    optional: ["Pali Twin Falls", "Beach afterward", "Pool day", "Photo memory wall update"],
    tags: ["Relaxing", "Low crowds", "Beach", "Teen friendly"],
    schedule: [
      { time: "Morning", plan: "Resort breakfast and slow start." },
      { time: "Midday", plan: "Option A: Ko Olina lagoons. Option B: Pali Twin Falls plus beach afterward." },
      { time: "Sunset", plan: "Sunset dinner and memory wall uploads." }
    ]
  },
  {
    id: "thu-resort",
    date: "Thursday, May 28",
    title: "Full Resort Recovery",
    theme: "Spa, pool, golf, local food, and no pressure.",
    wakeUp: "No alarm unless someone has a tee time.",
    hero: "https://commons.wikimedia.org/wiki/Special:FilePath/Aerial%20view%20of%20Disneys%20Aulani%20resort%20and%20Ko%20Olina%20Lagoon.jpg?width=1600",
    difficulty: "Flexible",
    walking: "As little or as much as wanted",
    teenFriendly: true,
    noPermit: true,
    driveTime: "Kakaʻako local food/brewery optional outing: 35-55 min each way",
    parking: "Keep the city outing optional and food-focused.",
    crowdTip: "Protect the recovery day. One optional outing max.",
    trail: "Lagoon walk",
    beach: "Ko Olina lagoons",
    food: ["Resort lunch", "Sunset dinner"],
    optional: ["Spa", "Pool", "Golf", "Kakaʻako local food", "Made in Hawaii tasting stop"],
    tags: ["Relaxing", "Low crowds", "Beach", "Scenic"],
    schedule: [
      { time: "Morning", plan: "Spa, golf, pool, or beach." },
      { time: "Afternoon", plan: "Optional Kakaʻako local food, brewery, or Made in Hawaii stop." },
      { time: "Evening", plan: "Final sunset dinner and favorite moments." }
    ]
  },
  {
    id: "fri-departure",
    date: "Friday, May 29",
    title: "Departure Day",
    theme: "Easy breakfast, one last lagoon walk, then airport rhythm.",
    wakeUp: "Keep the morning open around flight timing.",
    hero: "https://commons.wikimedia.org/wiki/Special:FilePath/Ko%20Olina%20Lagoon%20%28137451511%29.jpeg?width=1600",
    difficulty: "Flexible",
    walking: "0.5-1 mile",
    teenFriendly: true,
    noPermit: true,
    driveTime: "Ko Olina to HNL: 25-45 min depending on traffic",
    parking: "Build time for rental car return and luggage.",
    crowdTip: "Do not schedule a real outing on departure day.",
    trail: "Final lagoon walk",
    beach: "Ko Olina lagoon",
    food: ["Relaxed resort breakfast"],
    optional: ["Final family photo", "Grab snacks for airport"],
    tags: ["Relaxing", "Beach", "Low crowds"],
    schedule: [
      { time: "Morning", plan: "Relaxed breakfast and final packing." },
      { time: "Late morning", plan: "One last lagoon walk or pool sit." },
      { time: "Departure", plan: "Rental car return and airport departure." }
    ]
  }
];

export const places: Place[] = [
  { id: "resort", name: resort.name, category: "resort", address: resort.address, driveFromResort: "Home base", tags: ["Relaxing", "Beach"], lat: 21.3269, lng: -158.1206 },
  { id: "costco", name: "Costco Kapolei", category: "food", day: "Friday", address: "4589 Kapolei Pkwy, Kapolei, HI", driveFromResort: "12-18 min", tags: ["Arrival", "Groceries"], lat: 21.3327, lng: -158.0792 },
  { id: "judd", name: "Judd Trail", category: "trail", day: "Saturday", address: "Nuuanu Pali Dr, Honolulu, HI", driveFromResort: "45-60 min", tags: ["Waterfall", "Easy"], lat: 21.3601, lng: -157.8146 },
  { id: "pali", name: "Pali Twin Falls", category: "trail", day: "Saturday", address: "Nuʻuanu, Honolulu, HI", driveFromResort: "45-60 min", tags: ["Waterfall", "Adventure"], lat: 21.3629, lng: -157.8006 },
  { id: "lanikai", name: "Lanikai Beach", category: "beach", day: "Saturday", address: "Mokulua Dr, Kailua, HI", driveFromResort: "60-75 min", tags: ["Beach", "Scenic"], lat: 21.3925, lng: -157.7151 },
  { id: "kailua", name: "Kailua Beach", category: "beach", day: "Saturday", address: "526 Kawailoa Rd, Kailua, HI", driveFromResort: "55-70 min", tags: ["Beach", "Teen friendly"], lat: 21.3975, lng: -157.7278 },
  { id: "boots", name: "Boots & Kimo's", category: "food", day: "Saturday", address: "1020 Keolu Dr, Kailua, HI", driveFromResort: "60-75 min", tags: ["Breakfast"], lat: 21.3788, lng: -157.7392 },
  { id: "kalapawai", name: "Kalapawai Market", category: "food", day: "Saturday", address: "306 S Kalaheo Ave, Kailua, HI", driveFromResort: "55-70 min", tags: ["Lunch", "Coffee"], lat: 21.3941, lng: -157.7439 },
  { id: "ululani-kailua", name: "Ululani's Hawaiian Shave Ice", category: "shaved-ice", day: "Saturday", address: "Kailua, HI", driveFromResort: "55-70 min", tags: ["Shaved ice"], lat: 21.3932, lng: -157.7435 },
  { id: "manoa", name: "Aihualama / Mānoa Area", category: "trail", day: "Sunday", address: "Mānoa Valley, Honolulu, HI", driveFromResort: "35-50 min", tags: ["Waterfall", "Scenic"], lat: 21.3334, lng: -157.8015 },
  { id: "waimanalo", name: "Waimānalo Beach", category: "beach", day: "Sunday/Tuesday", address: "41-741 Kalanianaole Hwy, Waimānalo, HI", driveFromResort: "55-75 min", tags: ["Beach", "Relaxing"], lat: 21.3367, lng: -157.7006 },
  { id: "ono", name: "Ono Seafood", category: "food", day: "Sunday", address: "747 Kapahulu Ave, Honolulu, HI", driveFromResort: "35-50 min", tags: ["Lunch", "Poke"], lat: 21.2806, lng: -157.8137 },
  { id: "fresh-catch", name: "Fresh Catch", category: "food", day: "Sunday", address: "3109 Waialae Ave, Honolulu, HI", driveFromResort: "35-50 min", tags: ["Lunch", "Poke"], lat: 21.2894, lng: -157.8081 },
  { id: "waimea-bay", name: "Waimea Bay", category: "beach", day: "Monday", address: "61-031 Kamehameha Hwy, Haleiwa, HI", driveFromResort: "45-60 min", tags: ["Beach", "Scenic"], lat: 21.6408, lng: -158.0631 },
  { id: "waimea-valley", name: "Waimea Valley", category: "trail", day: "Monday", address: "59-864 Kamehameha Hwy, Haleiwa, HI", driveFromResort: "45-60 min", tags: ["Easy", "Waterfall"], lat: 21.6383, lng: -158.0503 },
  { id: "sharks-cove", name: "Shark's Cove", category: "beach", day: "Monday", address: "Pupukea, HI", driveFromResort: "50-65 min", tags: ["Adventure", "Beach"], lat: 21.6497, lng: -158.0636 },
  { id: "sunset-beach", name: "Sunset Beach", category: "beach", day: "Monday", address: "Sunset Beach, HI", driveFromResort: "55-70 min", tags: ["Scenic", "Beach"], lat: 21.6794, lng: -158.0417 },
  { id: "ululani-haleiwa", name: "Ululani's Hawaiian Shave Ice", category: "shaved-ice", day: "Monday", address: "Haleʻiwa, HI", driveFromResort: "35-50 min", tags: ["Shaved ice"], lat: 21.5923, lng: -158.1034 },
  { id: "giovannis", name: "Giovanni's Shrimp Truck", category: "food", day: "Monday", address: "66-472 Kamehameha Hwy, Haleiwa, HI", driveFromResort: "40-55 min", tags: ["Shrimp trucks", "Lunch"], lat: 21.5931, lng: -158.1037 },
  { id: "coffee-gallery", name: "Coffee Gallery", category: "food", day: "Monday", address: "66-250 Kamehameha Hwy, Haleiwa, HI", driveFromResort: "40-55 min", tags: ["Coffee"], lat: 21.5907, lng: -158.1046 },
  { id: "turtle-bay-golf", name: "Turtle Bay Golf", category: "golf", day: "Monday", address: "57-091 Kamehameha Hwy, Kahuku, HI", driveFromResort: "65-85 min", tags: ["Golf", "Ocean Views", "North Shore"], lat: 21.7034, lng: -157.9974 },
  { id: "makapuu", name: "Makapuʻu Lighthouse Trail", category: "trail", day: "Tuesday", address: "Kalanianaole Hwy, Waimānalo, HI", driveFromResort: "55-75 min", tags: ["Easy", "Scenic", "Early morning"], lat: 21.3094, lng: -157.6492 },
  { id: "sandy", name: "Sandy Beach", category: "beach", day: "Tuesday", address: "8801 Kalanianaole Hwy, Honolulu, HI", driveFromResort: "50-70 min", tags: ["Beach", "Viewing"], lat: 21.2851, lng: -157.6722 },
  { id: "lulumahu", name: "Lulumahu Falls Permit Candidate", category: "trail", day: "Tuesday", address: "Nuʻuanu, Honolulu, HI", driveFromResort: "40-55 min", tags: ["Permit required", "Waterfall"], lat: 21.3522, lng: -157.8139 },
  { id: "aloha-beer", name: "Aloha Beer Company", category: "brewery", day: "Tuesday/Thursday", address: "700 Queen St, Honolulu, HI", driveFromResort: "35-50 min", tags: ["Brewery", "Optional"], lat: 21.3012, lng: -157.8585 },
  { id: "kakaako-local-food", name: "Kakaʻako Local Food + Brewery Area", category: "made-in-hawaii", day: "Thursday", address: "Kakaʻako, Honolulu, HI", driveFromResort: "35-55 min", tags: ["Local food", "Brewery", "Made in Hawaii"], lat: 21.2984, lng: -157.8607 }
];

export const foodCategories = [
  "Local Hawaiian food",
  "Shrimp trucks",
  "Breakfast",
  "Lunch",
  "Dinner",
  "Shaved ice",
  "Coffee",
  "Breweries",
  "Farmers markets",
  "Poke",
  "Desserts"
];

export const beaches: Beach[] = [
  {
    id: "kailua-beach",
    name: "Kailua Beach Park",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Kailua%20Beach%20Park%20-%20Oahu%20-%20Hawaii.jpg?width=1200",
    crowd: "Medium",
    parking: "Medium",
    snorkeling: "Light",
    swimming: "Generally family-friendly when conditions are calm",
    amenities: "Bathrooms, showers, picnic areas",
    familyScore: 5,
    sunsetScore: 2,
    notes: "Best logistics on the Kailua side; easier than Lanikai for a family group.",
    tags: ["Beach", "Teen friendly", "Bathrooms"]
  },
  {
    id: "lanikai",
    name: "Lanikai Beach",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Lanikai%20Beach.jpg?width=1200",
    crowd: "High",
    parking: "Hard",
    snorkeling: "Light reef viewing",
    swimming: "Beautiful, but parking and access are the friction",
    amenities: "No bathrooms/showers at beach access",
    familyScore: 3,
    sunsetScore: 2,
    notes: "Use as a photo stop if parking feels stressful.",
    tags: ["Scenic", "Beach"]
  },
  {
    id: "waimanalo",
    name: "Waimānalo Beach",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Waimanalo%20Beach%20%2827829441405%29.jpg?width=1200",
    crowd: "Low",
    parking: "Medium",
    snorkeling: "Minimal",
    swimming: "Good room to spread out; check wind and shorebreak",
    amenities: "Bathrooms and showers at park areas",
    familyScore: 5,
    sunsetScore: 2,
    notes: "Great fit for relaxed, spacious family beach time.",
    tags: ["Low crowds", "Relaxing", "Beach"]
  },
  {
    id: "waimea",
    name: "Waimea Bay",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Waimea%20Bay%20Beach%20%2812598985244%29.jpg?width=1200",
    crowd: "High",
    parking: "Hard",
    snorkeling: "Seasonal",
    swimming: "Only when surf is calm; respect lifeguard guidance",
    amenities: "Bathrooms and showers",
    familyScore: 4,
    sunsetScore: 4,
    notes: "Arrive early or keep it as a scenic stop.",
    tags: ["North Shore", "Scenic"]
  },
  {
    id: "ko-olina",
    name: "Ko Olina Lagoons",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Ko%20Olina%20Lagoon%203.jpg?width=1200",
    crowd: "Medium",
    parking: "Easy",
    snorkeling: "Calm beginner-friendly water",
    swimming: "Protected lagoon setting",
    amenities: "Resort amenities nearby",
    familyScore: 5,
    sunsetScore: 5,
    notes: "Best recovery-day beach choice and easiest with all ages.",
    tags: ["Relaxing", "Sunset", "Family"]
  }
];

export const trails: Trail[] = [
  {
    id: "judd",
    name: "Judd Trail",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Rainforest_on_Manoa_Falls_trail,_Oahu,_Hawaii_-_panoramio.jpg?width=1200",
    distance: "1.0-1.5 miles",
    time: "45-75 min",
    difficulty: "Easy",
    permit: "No permit",
    mud: "Medium",
    streams: "Yes, small crossings",
    crowd: "Medium",
    parking: "Medium",
    nearbyFood: "Kailua or Honolulu lunch",
    beachPairing: "Kailua Beach Park",
    notes: "Short, shaded jungle loop with stream crossings. Best after checking recent rain.",
    tags: ["Waterfall", "Jungle", "Teen friendly", "No permit"]
  },
  {
    id: "aihualama",
    name: "Aihualama Partial Route",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Manoa_falls_entrance_of_trail.jpg?width=1200",
    distance: "Up to 2.8 miles",
    time: "75-120 min",
    difficulty: "Easy-Moderate",
    permit: "No permit",
    mud: "High",
    streams: "Possible wet sections",
    crowd: "Medium",
    parking: "Medium",
    nearbyFood: "Ono Seafood or Fresh Catch",
    beachPairing: "Waimānalo Beach",
    notes: "Use a partial route to keep the day relaxed and avoid overexertion.",
    tags: ["Jungle", "Scenic", "No permit"]
  },
  {
    id: "pali-twin",
    name: "Pali Twin Falls Candidate",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Manoa_Falls_Hawaii.jpg?width=1200",
    distance: "Under 2 miles target",
    time: "60-90 min",
    difficulty: "Easy-Moderate",
    permit: "No permit",
    mud: "Medium",
    streams: "Likely",
    crowd: "Low",
    parking: "Medium",
    nearbyFood: "Kailua side",
    beachPairing: "Kailua or Waimānalo",
    notes: "Flexible waterfall option for Wednesday if the family wants a second adventure.",
    tags: ["Waterfall", "Low crowds", "No permit"]
  },
  {
    id: "lulumahu",
    name: "Lulumahu Falls",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Waimea_Valley_Audubon_Center,_Oahu,_Hawaii_-_waterfall_view.JPG?width=1200",
    distance: "~2.5 miles",
    time: "2-3 hours",
    difficulty: "Moderate",
    permit: "Permit required",
    mud: "High",
    streams: "Multiple",
    crowd: "Medium",
    parking: "Hard",
    nearbyFood: "Adela's or Fresh Catch",
    beachPairing: "Kailua or Waimānalo",
    notes: "Not a default pick because it conflicts with the no-permit preference. Keep only if the family intentionally handles permits.",
    tags: ["Waterfall", "Permit required", "Jungle"]
  }
];

const marketPhoto = "https://commons.wikimedia.org/wiki/Special:FilePath/Kailua%20Beach%20Park%20-%20Oahu%20-%20Hawaii.jpg?width=1000";

export const farmerMarkets: FarmerMarket[] = [
  {
    id: "kekaulike-market",
    name: "Kekaulike Market in Chinatown",
    days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    hours: "7am-3pm",
    location: "Chinatown Honolulu",
    address: "1039 Kekaulike St, Honolulu, HI 96817",
    region: "Honolulu",
    lat: 21.3122,
    lng: -157.8629,
    photo: marketPhoto,
    nearby: { beaches: ["Ala Moana Beach Park"], trails: ["Aihualama / Mānoa Area"], food: ["Ono Seafood", "Fresh Catch"] },
    bestItineraryDays: ["Sunday", "Thursday"],
    recommendedStop: "Best as a city-side add-on after Mānoa or before Kakaʻako local food.",
    driveFromResort: "35-50 min",
    parkingWarning: "Chinatown parking can be tight; use garages and keep valuables out of sight."
  },
  {
    id: "city-square-marketplace",
    name: "Marketplace at City Square",
    days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    hours: "8am-4pm",
    location: "City Square Shopping Center",
    address: "1199 Dillingham Blvd, Honolulu, HI 96817",
    region: "Honolulu",
    lat: 21.3221,
    lng: -157.8758,
    photo: marketPhoto,
    nearby: { beaches: ["Ala Moana Beach Park"], trails: ["Aihualama / Mānoa Area"], food: ["Kakaʻako food stops"] },
    bestItineraryDays: ["Sunday", "Thursday"],
    recommendedStop: "Works on town days when the family is already crossing Honolulu.",
    driveFromResort: "30-45 min"
  },
  {
    id: "waikiki-makers-4",
    name: "Waikīkī Makers Market",
    days: ["Monday"],
    hours: "4-8pm",
    location: "Waikīkī",
    address: "2330 Kalākaua Ave, Honolulu, HI 96815",
    region: "Waikiki",
    lat: 21.2794,
    lng: -157.8293,
    photo: marketPhoto,
    nearby: { beaches: ["Waikīkī Beach"], trails: ["Diamond Head area"], food: ["Waikīkī restaurants"] },
    bestItineraryDays: ["Thursday"],
    recommendedStop: "Optional only if the family wants an evening Waikīkī outing.",
    driveFromResort: "40-65 min",
    parkingWarning: "Waikīkī parking and return traffic can be slow."
  },
  {
    id: "waikiki-farmers-hyatt",
    name: "Waikiki Farmers Market",
    days: ["Monday", "Wednesday"],
    hours: "4-8pm",
    location: "Hyatt Regency Waikiki Beach Resort",
    address: "2424 Kalākaua Ave, Honolulu, HI 96815",
    region: "Waikiki",
    lat: 21.2766,
    lng: -157.8257,
    photo: marketPhoto,
    nearby: { beaches: ["Waikīkī Beach"], trails: ["Diamond Head area"], food: ["Waikīkī restaurants"] },
    bestItineraryDays: ["Wednesday", "Thursday"],
    recommendedStop: "Evening city add-on; not ideal after North Shore.",
    driveFromResort: "40-65 min",
    parkingWarning: "Plan paid parking and avoid late-afternoon H-1 if possible."
  },
  {
    id: "waikiki-makers-5",
    name: "Waikiki Makers Market",
    days: ["Monday"],
    hours: "5-9pm",
    location: "Waikīkī",
    address: "2330 Kalākaua Ave, Honolulu, HI 96815",
    region: "Waikiki",
    lat: 21.2794,
    lng: -157.8293,
    photo: marketPhoto,
    nearby: { beaches: ["Waikīkī Beach"], trails: ["Diamond Head area"], food: ["Waikīkī restaurants"] },
    bestItineraryDays: ["Thursday"],
    recommendedStop: "Treat as an optional evening market if the group wants city energy.",
    driveFromResort: "40-65 min",
    parkingWarning: "Waikīkī parking can be expensive."
  },
  {
    id: "fort-street-open-market",
    name: "Fort Street Mall Open Market",
    days: ["Tuesday", "Friday"],
    hours: "7am-1:30pm",
    location: "Fort Street Mall",
    address: "Fort Street Mall, Honolulu, HI 96813",
    region: "Honolulu",
    lat: 21.3103,
    lng: -157.8608,
    photo: marketPhoto,
    nearby: { beaches: ["Ala Moana Beach Park"], trails: ["Aihualama / Mānoa Area"], food: ["Downtown lunch"] },
    bestItineraryDays: ["Friday", "Tuesday"],
    recommendedStop: "Useful if arriving/departing through town, but not worth a separate drive.",
    driveFromResort: "35-50 min"
  },
  {
    id: "makeke-iki-waianae",
    name: "Mākeke ʻIki at Waiʻanae",
    days: ["Tuesday"],
    hours: "9am-12pm",
    location: "Waiʻanae Coast Comprehensive Health Center",
    address: "86-260 Farrington Hwy, Waiʻanae, HI 96792",
    region: "West Side",
    lat: 21.4465,
    lng: -158.184,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Ko%20Olina%20Lagoon%203.jpg?width=1000",
    nearby: { beaches: ["Ko Olina Lagoons", "West side beaches"], trails: ["Lagoon walk"], food: ["Ko Olina restaurants"] },
    bestItineraryDays: ["Tuesday", "Wednesday", "Thursday"],
    recommendedStop: "Best west-side fit when staying close to Ko Olina.",
    driveFromResort: "25-35 min"
  },
  {
    id: "kaiser-ptsa",
    name: "Kaiser PTSA Farmers Market",
    days: ["Tuesday"],
    hours: "4-6pm",
    location: "Kaiser High School",
    address: "511 Lunalilo Home Rd, Honolulu, HI 96825",
    region: "East Honolulu",
    lat: 21.2872,
    lng: -157.7045,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Lanikai%20Beach.jpg?width=1000",
    nearby: { beaches: ["Sandy Beach", "Waimānalo Beach"], trails: ["Makapuʻu area"], food: ["East Honolulu casual food"] },
    bestItineraryDays: ["Tuesday"],
    recommendedStop: "Possible after east-side beach time, but only if the family is still nearby late afternoon.",
    driveFromResort: "55-75 min"
  },
  {
    id: "bayview-night-market",
    name: "Bayview Night Market",
    days: ["Tuesday"],
    hours: "4-8pm",
    location: "Bay View area, Kāneʻohe",
    address: "45-285 Kāneʻohe Bay Dr, Kāneʻohe, HI 96744",
    region: "Windward",
    lat: 21.407,
    lng: -157.798,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Kailua%20Beach%20Park%20-%20Oahu%20-%20Hawaii.jpg?width=1000",
    nearby: { beaches: ["Kailua Beach Park"], trails: ["Judd Trail", "Pali Twin Falls"], food: ["Kailua restaurants"] },
    bestItineraryDays: ["Saturday", "Tuesday"],
    recommendedStop: "Windward evening option if already returning from Kailua/Kāneʻohe.",
    driveFromResort: "45-65 min"
  },
  {
    id: "manoa-marketplace",
    name: "The Farmers Market at Mānoa Marketplace",
    days: ["Tuesday", "Thursday", "Sunday"],
    hours: "7am-2pm",
    location: "Mānoa Marketplace",
    address: "2752 Woodlawn Dr, Honolulu, HI 96822",
    region: "Honolulu",
    lat: 21.3099,
    lng: -157.8095,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Waimanalo%20Beach%20%2827829441405%29.jpg?width=1000",
    nearby: { beaches: ["Waimānalo Beach"], trails: ["Aihualama / Mānoa Area"], food: ["Ono Seafood", "Fresh Catch"] },
    bestItineraryDays: ["Sunday"],
    recommendedStop: "Excellent match for the Dole + Aihualama + Waimānalo day.",
    driveFromResort: "35-50 min",
    parkingWarning: "Arrive early for easier Mānoa parking."
  },
  {
    id: "aloha-stadium",
    name: "Aloha Stadium Swap Meet & Marketplace",
    days: ["Wednesday", "Saturday", "Sunday"],
    hours: "Wed/Sat 8am-3pm; Sun 6:30am-3pm",
    location: "Aloha Stadium",
    address: "99-500 Salt Lake Blvd, Aiea, HI 96701",
    region: "Central",
    lat: 21.3726,
    lng: -157.9298,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Ko%20Olina%20Lagoon%203.jpg?width=1000",
    nearby: { beaches: ["Ko Olina Lagoons", "Ala Moana Beach Park"], trails: ["Lagoon walk"], food: ["Pearlridge/Aiea food"] },
    bestItineraryDays: ["Wednesday", "Saturday"],
    recommendedStop: "Good central stop between Ko Olina and Honolulu/Windward routes.",
    driveFromResort: "20-30 min"
  },
  {
    id: "mini-artfest-marriott",
    name: "Mini Artfest at Marriott Ko Olina Beach Club",
    days: ["Wednesday", "Friday"],
    hours: "9am-4pm",
    location: "Marriott's Ko Olina Beach Club",
    address: resort.address,
    region: "West Side",
    lat: 21.3269,
    lng: -158.1206,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Aerial%20view%20of%20Disneys%20Aulani%20resort%20and%20Ko%20Olina%20Lagoon.jpg?width=1000",
    nearby: { beaches: ["Ko Olina Lagoons"], trails: ["Lagoon walk"], food: ["Monkeypod Kitchen", "Longboards Bar & Grill"] },
    bestItineraryDays: ["Wednesday", "Friday"],
    recommendedStop: "Best low-effort market because it is at the home base.",
    driveFromResort: "At resort"
  },
  {
    id: "north-shore-country",
    name: "North Shore Country Market",
    days: ["Wednesday"],
    hours: "1-6pm",
    location: "Sunset Beach area",
    address: "59-360 Kamehameha Hwy, Haleʻiwa, HI 96712",
    region: "North Shore",
    lat: 21.667,
    lng: -158.052,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Waimea%20Bay%20Beach%20%2812598985244%29.jpg?width=1000",
    nearby: { beaches: ["Sunset Beach", "Waimea Bay"], trails: ["Waimea Valley area"], food: ["North Shore Tacos", "Giovanni's Shrimp Truck"] },
    bestItineraryDays: ["Monday", "Wednesday"],
    recommendedStop: "North Shore fit, but the current North Shore day is Monday; use only if schedule shifts.",
    driveFromResort: "55-75 min",
    parkingWarning: "North Shore roadside parking can be slow and crowded."
  },
  {
    id: "windward-mall",
    name: "Farmers Market at Windward Mall",
    days: ["Wednesday", "Sunday"],
    hours: "Wed 2-6pm; Sun 10am-2pm",
    location: "Windward Mall",
    address: "46-056 Kamehameha Hwy, Kāneʻohe, HI 96744",
    region: "Windward",
    lat: 21.418,
    lng: -157.805,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Kailua%20Beach%20Park%20-%20Oahu%20-%20Hawaii.jpg?width=1000",
    nearby: { beaches: ["Kailua Beach Park"], trails: ["Judd Trail", "Pali Twin Falls"], food: ["Kailua restaurants"] },
    bestItineraryDays: ["Saturday", "Sunday", "Wednesday"],
    recommendedStop: "Good windward backup if Kailua parking or weather changes plans.",
    driveFromResort: "45-65 min"
  },
  {
    id: "honolulu-farmers",
    name: "Honolulu Farmers Market",
    days: ["Wednesday"],
    hours: "4-7pm",
    location: "Neal S. Blaisdell Center",
    address: "777 Ward Ave, Honolulu, HI 96814",
    region: "Honolulu",
    lat: 21.3008,
    lng: -157.8506,
    photo: marketPhoto,
    nearby: { beaches: ["Ala Moana Beach Park"], trails: ["Aihualama / Mānoa Area"], food: ["Kakaʻako restaurants"] },
    bestItineraryDays: ["Wednesday", "Thursday"],
    recommendedStop: "Easy pairing with Kakaʻako local food or brewery stops.",
    driveFromResort: "35-50 min"
  },
  {
    id: "makana-ka-makana",
    name: "Makana Mkt. at Ka Makana Aliʻi",
    days: ["Wednesday", "Saturday", "Sunday"],
    hours: "Wed 4-8pm; Sat/Sun 11am-3pm",
    location: "Ka Makana Aliʻi",
    address: "91-5431 Kapolei Pkwy, Kapolei, HI 96707",
    region: "West Side",
    lat: 21.331,
    lng: -158.0904,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Ko%20Olina%20Lagoon%203.jpg?width=1000",
    nearby: { beaches: ["Ko Olina Lagoons"], trails: ["Lagoon walk"], food: ["Kapolei restaurants"] },
    bestItineraryDays: ["Friday", "Wednesday", "Thursday"],
    recommendedStop: "Best west-side grocery/snack add-on near Ko Olina.",
    driveFromResort: "12-18 min"
  },
  {
    id: "kailua-thursday",
    name: "Kailua Farmers Market",
    days: ["Thursday"],
    hours: "4-7pm",
    location: "Kailua town",
    address: "609 Kailua Rd, Kailua, HI 96734",
    region: "Windward",
    lat: 21.3925,
    lng: -157.7426,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Kailua%20Beach%20Park%20-%20Oahu%20-%20Hawaii.jpg?width=1000",
    nearby: { beaches: ["Kailua Beach Park", "Lanikai Beach"], trails: ["Judd Trail", "Pali Twin Falls"], food: ["Kalapawai Market"] },
    bestItineraryDays: ["Saturday", "Tuesday"],
    recommendedStop: "Ideal if the family moves Kailua-side plans to Thursday evening.",
    driveFromResort: "55-70 min",
    parkingWarning: "Kailua town parking is easier than Lanikai but still fills at peak times."
  },
  {
    id: "ono-grindz-makeke",
    name: "Ono Grindz & Mākeke Farmers Market",
    days: ["Thursday"],
    hours: "4-8pm",
    location: "West/Central Oʻahu pop-up market",
    address: "94-790 Lumiaina St, Waipahu, HI 96797",
    region: "Central",
    lat: 21.403,
    lng: -158.007,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Ko%20Olina%20Lagoon%203.jpg?width=1000",
    nearby: { beaches: ["Ko Olina Lagoons"], trails: ["Lagoon walk"], food: ["Kapolei/Waipahu food"] },
    bestItineraryDays: ["Thursday"],
    recommendedStop: "Central/west option for resort recovery day without crossing to Waikīkī.",
    driveFromResort: "20-30 min"
  },
  {
    id: "mahiku-mililani",
    name: "Mahiku Farmers Market",
    days: ["Friday"],
    hours: "3-7pm",
    location: "Mililani Shopping Center",
    address: "95-221 Kipapa Dr, Mililani, HI 96789",
    region: "Central",
    lat: 21.4502,
    lng: -158.0171,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Waimea%20Bay%20Beach%20%2812598985244%29.jpg?width=1000",
    nearby: { beaches: ["North Shore beaches"], trails: ["Waimea area"], food: ["Mililani casual food"] },
    bestItineraryDays: ["Monday"],
    recommendedStop: "Central stop only if North Shore timing shifts later in the week.",
    driveFromResort: "35-45 min"
  },
  {
    id: "kcc",
    name: "KCC Farmers Market",
    days: ["Saturday"],
    hours: "7:30-11am",
    location: "Kapiʻolani Community College",
    address: "4303 Diamond Head Rd, Honolulu, HI 96816",
    region: "Honolulu",
    lat: 21.2687,
    lng: -157.8022,
    photo: marketPhoto,
    nearby: { beaches: ["Waikīkī Beach"], trails: ["Diamond Head area"], food: ["Ono Seafood", "Fresh Catch"] },
    bestItineraryDays: ["Saturday"],
    recommendedStop: "Saturday option, but it pulls the family toward town before Kailua; use only if everyone wants a food-first morning.",
    driveFromResort: "45-60 min",
    parkingWarning: "Very popular; arrive early."
  },
  {
    id: "kakaako",
    name: "Kakaʻako Farmers Market",
    days: ["Saturday"],
    hours: "8am-12pm",
    location: "Kakaʻako",
    address: "919 Ala Moana Blvd, Honolulu, HI 96814",
    region: "Honolulu",
    lat: 21.2952,
    lng: -157.8599,
    photo: marketPhoto,
    nearby: { beaches: ["Ala Moana Beach Park"], trails: ["Mānoa area"], food: ["Kakaʻako restaurants"] },
    bestItineraryDays: ["Saturday", "Thursday"],
    recommendedStop: "Better for a town day than Kailua day; keep as optional.",
    driveFromResort: "35-50 min",
    parkingWarning: "Popular Saturday market with urban parking."
  },
  {
    id: "pearlridge",
    name: "Pearlridge Farmers Market",
    days: ["Saturday"],
    hours: "8am-12pm",
    location: "Pearlridge Center",
    address: "98-1005 Moanalua Rd, Aiea, HI 96701",
    region: "Central",
    lat: 21.385,
    lng: -157.943,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Ko%20Olina%20Lagoon%203.jpg?width=1000",
    nearby: { beaches: ["Ko Olina Lagoons"], trails: ["Lagoon walk"], food: ["Pearlridge/Aiea food"] },
    bestItineraryDays: ["Saturday", "Wednesday"],
    recommendedStop: "Central stop on the way between Ko Olina and Honolulu/Windward.",
    driveFromResort: "22-35 min"
  },
  {
    id: "makeke-waianae",
    name: "Mākeke Waiʻanae: Waianae Farmers Market",
    days: ["Saturday"],
    hours: "8am-12pm",
    location: "Waiʻanae Coast Comprehensive Health Center",
    address: "86-260 Farrington Hwy, Waiʻanae, HI 96792",
    region: "West Side",
    lat: 21.4465,
    lng: -158.184,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Ko%20Olina%20Lagoon%203.jpg?width=1000",
    nearby: { beaches: ["Ko Olina Lagoons", "West side beaches"], trails: ["Lagoon walk"], food: ["Ko Olina restaurants"] },
    bestItineraryDays: ["Saturday", "Wednesday"],
    recommendedStop: "Close-ish west-side alternative if skipping cross-island driving.",
    driveFromResort: "25-35 min"
  },
  {
    id: "waialua",
    name: "Waialua Farmers Market",
    days: ["Saturday"],
    hours: "8:30am-1pm",
    location: "Waialua",
    address: "67-106 Kealohanui St, Waialua, HI 96791",
    region: "North Shore",
    lat: 21.5742,
    lng: -158.1303,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Waimea%20Bay%20Beach%20%2812598985244%29.jpg?width=1000",
    nearby: { beaches: ["Waimea Bay", "Haleʻiwa"], trails: ["Waimea area"], food: ["Giovanni's Shrimp Truck", "Coffee Gallery"] },
    bestItineraryDays: ["Monday"],
    recommendedStop: "Great North Shore alignment if the day moves to Saturday.",
    driveFromResort: "40-55 min"
  },
  {
    id: "village-night-market",
    name: "Village Night Market",
    days: ["Saturday"],
    hours: "5-9pm",
    location: "Central/West Oʻahu night market",
    address: "94-790 Lumiaina St, Waipahu, HI 96797",
    region: "Central",
    lat: 21.403,
    lng: -158.007,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Ko%20Olina%20Lagoon%203.jpg?width=1000",
    nearby: { beaches: ["Ko Olina Lagoons"], trails: ["Lagoon walk"], food: ["Waipahu/Kapolei food"] },
    bestItineraryDays: ["Saturday", "Wednesday"],
    recommendedStop: "Evening option if the family wants a local market without Waikīkī.",
    driveFromResort: "20-30 min"
  },
  {
    id: "mililani",
    name: "Mililani Farmers Market",
    days: ["Sunday"],
    hours: "8-11am",
    location: "Mililani High School",
    address: "95-1200 Meheula Pkwy, Mililani, HI 96789",
    region: "Central",
    lat: 21.475,
    lng: -158.009,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Waimea%20Bay%20Beach%20%2812598985244%29.jpg?width=1000",
    nearby: { beaches: ["North Shore beaches"], trails: ["Waimea area"], food: ["Mililani casual food"] },
    bestItineraryDays: ["Sunday", "Monday"],
    recommendedStop: "Central stop if Sunday timing shifts before Mānoa.",
    driveFromResort: "35-45 min"
  },
  {
    id: "kailua-town-sunday",
    name: "KailuaTown Farmers Market",
    days: ["Sunday"],
    hours: "8am-12pm",
    location: "Kailua Elementary School",
    address: "315 Kuulei Rd, Kailua, HI 96734",
    region: "Windward",
    lat: 21.3971,
    lng: -157.7429,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Kailua%20Beach%20Park%20-%20Oahu%20-%20Hawaii.jpg?width=1000",
    nearby: { beaches: ["Kailua Beach Park", "Lanikai Beach"], trails: ["Judd Trail", "Pali Twin Falls"], food: ["Kalapawai Market"] },
    bestItineraryDays: ["Saturday", "Sunday"],
    recommendedStop: "Excellent Kailua-side pairing if the group swaps beach days.",
    driveFromResort: "55-70 min",
    parkingWarning: "Go early and keep Lanikai as optional."
  },
  {
    id: "aloha-market-waikiki",
    name: "Aloha Market at Waikiki",
    days: ["Sunday"],
    hours: "8am-2pm",
    location: "Waikīkī",
    address: "227 Lewers St, Honolulu, HI 96815",
    region: "Waikiki",
    lat: 21.2792,
    lng: -157.8317,
    photo: marketPhoto,
    nearby: { beaches: ["Waikīkī Beach"], trails: ["Diamond Head area"], food: ["Waikīkī restaurants"] },
    bestItineraryDays: ["Thursday"],
    recommendedStop: "Optional Waikīkī outing; not efficient for Ko Olina recovery days.",
    driveFromResort: "40-65 min",
    parkingWarning: "Waikīkī parking can be slow and costly."
  },
  {
    id: "lokahi-kailua",
    name: "Lōkahi Kailua Market",
    days: ["Sunday"],
    hours: "9am-1pm",
    location: "Kailua town",
    address: "340 Uluniu St, Kailua, HI 96734",
    region: "Windward",
    lat: 21.3945,
    lng: -157.7434,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Kailua%20Beach%20Park%20-%20Oahu%20-%20Hawaii.jpg?width=1000",
    nearby: { beaches: ["Kailua Beach Park", "Lanikai Beach"], trails: ["Judd Trail", "Pali Twin Falls"], food: ["Kalapawai Market"] },
    bestItineraryDays: ["Saturday", "Sunday"],
    recommendedStop: "Good Kailua-side Sunday option with beach nearby.",
    driveFromResort: "55-70 min"
  },
  {
    id: "market-on-the-ranch",
    name: "Market on the Ranch",
    days: ["Sunday"],
    hours: "11am-3pm",
    location: "Turtle Bay / Kahuku area",
    address: "57-091 Kamehameha Hwy, Kahuku, HI 96731",
    region: "North Shore",
    lat: 21.7034,
    lng: -157.9974,
    photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Waimea%20Bay%20Beach%20%2812598985244%29.jpg?width=1000",
    nearby: { beaches: ["Sunset Beach", "Waimea Bay"], trails: ["Waimea area"], food: ["North Shore food trucks"] },
    bestItineraryDays: ["Monday"],
    recommendedStop: "North Shore fit only if the North Shore day moves to Sunday.",
    driveFromResort: "65-85 min",
    parkingWarning: "Longer return drive; leave before late afternoon if possible."
  }
];

export const routePlans: RoutePlan[] = [
  {
    dayId: "fri-arrival",
    label: "Day 1 Arrival",
    color: "#2f80ed",
    leaveBy: "After landing; leave airport before afternoon traffic if bags arrive quickly.",
    totalDrive: "45-75 min including Costco",
    trafficNote: "H-1 westbound can build in late afternoon; keep the day simple.",
    parkingWarnings: ["Airport rental car timing", "Costco lot can be busy"],
    scenicPins: ["Ko Olina sunset walk"],
    stops: ["resort", "costco", "makana-ka-makana", "mini-artfest-marriott", "ko-olina-golf-club"]
  },
  {
    dayId: "sat-kailua",
    label: "Day 2 Kailua",
    color: "#3f7f5f",
    leaveBy: "6:45 AM",
    totalDrive: "2-2.5 hr round trip plus stops",
    trafficNote: "Cross-island early; return after lunch before late-afternoon buildup.",
    parkingWarnings: ["Lanikai parking is difficult", "Kailua town lots fill around lunch"],
    scenicPins: ["Nuʻuanu Pali Lookout"],
    stops: ["resort", "judd", "kailua", "ululani-kailua", "kailua-town-sunday", "windward-mall", "mano-chocolate", "royal-hawaiian-golf-club"]
  },
  {
    dayId: "sun-manoa",
    label: "Day 3 Mānoa/Waimānalo",
    color: "#f7b267",
    leaveBy: "7:00 AM",
    totalDrive: "2.5-3.25 hr loop",
    trafficNote: "Avoid returning west through Honolulu at peak commute when possible.",
    parkingWarnings: ["Mānoa trail parking can be tight", "Keep beach valuables hidden"],
    scenicPins: ["Nuʻuanu Pali Lookout"],
    stops: ["resort", "manoa-marketplace", "manoa", "ono", "fresh-catch", "waimanalo", "ono-seafood-poke"]
  },
  {
    dayId: "mon-north-shore",
    label: "Day 4 North Shore",
    color: "#8d5cf6",
    leaveBy: "7:00 AM",
    totalDrive: "2-3 hr depending on loop",
    trafficNote: "Pick two anchor stops and avoid chasing every beach.",
    parkingWarnings: ["Waimea Bay fills quickly", "Shark's Cove roadside parking is limited"],
    scenicPins: ["Haleʻiwa town", "Sunset Beach"],
    stops: ["resort", "waimea-bay", "sharks-cove", "sunset-beach", "giovannis", "coffee-gallery", "waialua", "market-on-the-ranch", "green-world-coffee", "giovannis-shrimp", "turtle-bay-golf-course"]
  },
  {
    dayId: "tue-lulumahu-review",
    label: "Day 5 Falls Candidate",
    color: "#f26b5e",
    leaveBy: "6:45 AM",
    totalDrive: "2-3 hr depending on selected legal trail",
    trafficNote: "Confirm permits before choosing Lulumahu; otherwise keep to no-permit alternatives.",
    parkingWarnings: ["Lulumahu requires permit review", "Windward beach parking gets harder late morning"],
    scenicPins: ["Pali scenic pullouts"],
    stops: ["resort", "lulumahu", "waimanalo", "aloha-beer", "kaiser-ptsa", "bayview-night-market", "aloha-beer-production", "olomana-golf-links"]
  },
  {
    dayId: "wed-flex",
    label: "Day 6 Flexible",
    color: "#2aa7a5",
    leaveBy: "No alarm unless choosing Pali Twin Falls.",
    totalDrive: "0-2 hr depending on option",
    trafficNote: "Favor west-side or central markets if staying relaxed.",
    parkingWarnings: ["Keep outing count low"],
    scenicPins: ["Ko Olina sunset"],
    stops: ["resort", "mini-artfest-marriott", "makana-ka-makana", "aloha-stadium", "pearlridge", "ko-hana-rum", "ko-olina-golf-club", "royal-kunia-country-club"]
  },
  {
    dayId: "thu-resort",
    label: "Day 7 Resort",
    color: "#d9a441",
    leaveBy: "Late morning only if doing Kakaʻako local food or brewery.",
    totalDrive: "0-2 hr optional",
    trafficNote: "If heading to town, keep it local-food focused and avoid the late-afternoon return west.",
    parkingWarnings: ["Urban Kakaʻako parking varies by event", "Skip retail-focused detours"],
    scenicPins: ["Kakaʻako murals", "Ko Olina sunset"],
    stops: ["resort", "kakaako-local-food", "honolulu-farmers", "ono-grindz-makeke", "honolulu-beerworks", "aloha-beer-production", "ko-olina-golf-club"]
  },
  {
    dayId: "fri-departure",
    label: "Day 8 Departure",
    color: "#64748b",
    leaveBy: "Leave Ko Olina 2.5-3 hours before flight time, earlier if checking bags.",
    totalDrive: "25-45 min to HNL plus rental return",
    trafficNote: "Keep this route simple: resort, final lagoon walk, airport.",
    parkingWarnings: ["Avoid adding a real outing", "Build time for rental car return"],
    scenicPins: ["Final Ko Olina lagoon walk"],
    stops: ["resort", "mini-artfest-marriott"]
  }
];

export const adHocFarmersMarkets = [
  "Aloha Home Market",
  "Aloun Country Market",
  "Art+Flea Hawaii's Favorite Urban Market",
  "DoHo Night Market",
  "Farmers Market at Hoʻopili Community Association",
  "Hana Hou Makeke: Vintage Hawaiian Market",
  "Harbors Vintage Vintage Market",
  "Hawaiʻi's Shop Local Pop-up",
  "Honolulu Makers Market",
  "Honolulu Night Market",
  "Hoʻomau Market",
  "Kaimukī Night Market",
  "Kaiāulu Market",
  "Keiki Makers Market",
  "Koʻolau Night Market",
  "Kaiwiʻula Night Market",
  "Māʻona Market",
  "Mākia Market",
  "Mālama Hawaiʻi Makers Market",
  "Maunawili Night Market",
  "New Wave Night Market",
  "Night Market Central at Pearl at Kalauao",
  "Sunshine People Market",
  "Taste of Aloha Night Market",
  "Taste of Makaha Night Market",
  "The Blessed Friday Market",
  "The Mom Made Market Hawaii",
  "Vintage Night Market at Koko Marina Center",
  "What the Truck?! at Waikele"
];

const oahuScenicPhoto = "https://commons.wikimedia.org/wiki/Special:FilePath/Aerial%20view%20of%20Disneys%20Aulani%20resort%20and%20Ko%20Olina%20Lagoon.jpg?width=1000";
const northShorePhoto = "https://commons.wikimedia.org/wiki/Special:FilePath/Waimea%20Bay%20Beach%20%2812598985244%29.jpg?width=1000";
const windwardPhoto = "https://commons.wikimedia.org/wiki/Special:FilePath/Kailua%20Beach%20Park%20-%20Oahu%20-%20Hawaii.jpg?width=1000";

export const madeInHawaiiLocations: MadeInHawaiiLocation[] = [
  {
    id: "dole-plantation",
    name: "Dole Plantation",
    category: "pineapple",
    address: "64-1550 Kamehameha Hwy, Wahiawā, HI 96786",
    region: "Central Oʻahu",
    lat: 21.525,
    lng: -158.037,
    photoGallery: [northShorePhoto, oahuScenicPhoto],
    onsiteProduction: true,
    familyFriendly: true,
    tasting: "Pineapple treats and Dole Whip-style snacks",
    duration: "30-75 min",
    itineraryCompatibility: ["Sunday Dole + Aihualama", "North Shore day"],
    scenicValue: 4,
    notes: "Best as a quick agriculture-themed stop rather than a full-day tourist attraction.",
    mapQuery: "Dole Plantation Oahu"
  },
  {
    id: "green-world-coffee",
    name: "Green World Coffee Farm",
    category: "coffee",
    address: "71-101 Kamehameha Hwy, Wahiawā, HI 96786",
    region: "Central Oʻahu",
    lat: 21.538,
    lng: -158.035,
    photoGallery: [northShorePhoto, oahuScenicPhoto],
    onsiteProduction: true,
    familyFriendly: true,
    tasting: "Coffee samples; onsite roasting/coffee farm experience",
    duration: "20-45 min",
    itineraryCompatibility: ["North Shore day", "Dole quick stop"],
    scenicValue: 4,
    notes: "Ranks high because it is local, quick, and fits the Ko Olina-to-North-Shore route.",
    mapQuery: "Green World Coffee Farm Wahiawa"
  },
  {
    id: "mano-chocolate",
    name: "Mānoa Chocolate",
    category: "cacao",
    address: "315 Uluniu St, Kailua, HI 96734",
    region: "Windward",
    lat: 21.394,
    lng: -157.743,
    photoGallery: [windwardPhoto, oahuScenicPhoto],
    onsiteProduction: true,
    familyFriendly: true,
    tasting: "Chocolate tasting and factory-style experience",
    duration: "30-75 min",
    itineraryCompatibility: ["Saturday Kailua side", "Tuesday beach day"],
    scenicValue: 4,
    notes: "Excellent local-production experience: cacao/chocolate in Kailua.",
    mapQuery: "Manoa Chocolate Kailua"
  },
  {
    id: "aloha-beer-production",
    name: "Aloha Beer Company",
    category: "brewery",
    address: "700 Queen St, Honolulu, HI 96813",
    region: "Kakaʻako / Honolulu",
    lat: 21.3012,
    lng: -157.8585,
    photoGallery: [oahuScenicPhoto],
    onsiteProduction: true,
    familyFriendly: true,
    tasting: "Local brewery taproom; verify current onsite brewing/tour availability",
    duration: "45-90 min",
    itineraryCompatibility: ["Tuesday optional brewery", "Thursday local food day"],
    scenicValue: 3,
    notes: "Included because it is a local brewery/taproom, not a generic bar.",
    mapQuery: "Aloha Beer Company Honolulu"
  },
  {
    id: "honolulu-beerworks",
    name: "Honolulu Beerworks",
    category: "brewery",
    address: "328 Cooke St, Honolulu, HI 96813",
    region: "Kakaʻako / Honolulu",
    lat: 21.2981,
    lng: -157.858,
    photoGallery: [oahuScenicPhoto],
    onsiteProduction: true,
    familyFriendly: true,
    tasting: "Local craft brewery taproom",
    duration: "45-90 min",
    itineraryCompatibility: ["Thursday local food day"],
    scenicValue: 3,
    notes: "Authentic brewery option for adults while staying food/local-production focused.",
    mapQuery: "Honolulu Beerworks"
  },
  {
    id: "ko-hana-rum",
    name: "Kō Hana Distillers",
    category: "distillery",
    address: "92-1770 Kunia Rd #227, Kunia Camp, HI 96759",
    region: "Central / West Side",
    lat: 21.456,
    lng: -158.064,
    photoGallery: [oahuScenicPhoto],
    onsiteProduction: true,
    familyFriendly: true,
    tasting: "Rum tasting for adults; sugarcane/agricultural production story",
    duration: "45-90 min",
    itineraryCompatibility: ["Wednesday flexible day", "Thursday resort day"],
    scenicValue: 4,
    notes: "Strong fit: local agricultural production, west-side convenience, and authentic Hawaii-made story.",
    mapQuery: "Ko Hana Distillers Kunia"
  },
  {
    id: "ululani-production",
    name: "Ululani's Hawaiian Shave Ice",
    category: "shave-ice",
    address: "Oʻahu location varies by route",
    region: "Route-dependent",
    lat: 21.3932,
    lng: -157.7435,
    photoGallery: [windwardPhoto],
    onsiteProduction: true,
    familyFriendly: true,
    tasting: "Shave ice",
    duration: "15-30 min",
    itineraryCompatibility: ["Saturday Kailua side", "North Shore day"],
    scenicValue: 3,
    notes: "Family dessert stop; keep this as the default shave ice brand throughout the planner.",
    mapQuery: "Ululani's Hawaiian Shave Ice Oahu"
  },
  {
    id: "ono-seafood-poke",
    name: "Ono Seafood",
    category: "poke",
    address: "747 Kapahulu Ave, Honolulu, HI 96816",
    region: "Honolulu",
    lat: 21.2806,
    lng: -157.8137,
    photoGallery: [windwardPhoto],
    onsiteProduction: true,
    familyFriendly: true,
    tasting: "Fresh poke bowls",
    duration: "20-40 min",
    itineraryCompatibility: ["Sunday Mānoa/Waimānalo"],
    scenicValue: 2,
    notes: "Local food production experience that pairs well with the Mānoa/Waimānalo route.",
    mapQuery: "Ono Seafood Honolulu"
  },
  {
    id: "giovannis-shrimp",
    name: "Giovanni's Shrimp Truck",
    category: "shrimp",
    address: "66-472 Kamehameha Hwy, Haleʻiwa, HI 96712",
    region: "North Shore",
    lat: 21.5931,
    lng: -158.1037,
    photoGallery: [northShorePhoto],
    onsiteProduction: true,
    familyFriendly: true,
    tasting: "Garlic shrimp plates",
    duration: "30-60 min",
    itineraryCompatibility: ["North Shore day"],
    scenicValue: 4,
    notes: "Scenic roadside food destination with strong North Shore route fit.",
    mapQuery: "Giovanni's Shrimp Truck Haleiwa"
  },
  {
    id: "tropical-farms",
    name: "Tropical Farms Macadamia Nuts",
    category: "macadamia",
    address: "49-227 Kamehameha Hwy, Kāneʻohe, HI 96744",
    region: "Windward",
    lat: 21.511,
    lng: -157.845,
    photoGallery: [windwardPhoto],
    onsiteProduction: true,
    familyFriendly: true,
    tasting: "Macadamia nut samples and local snacks",
    duration: "20-45 min",
    itineraryCompatibility: ["Saturday Kailua side", "Wednesday flexible adventure"],
    scenicValue: 4,
    notes: "Good local snack/agriculture stop if the route passes Kāneʻohe.",
    mapQuery: "Tropical Farms Macadamia Nuts Kaneohe"
  }
];

export const golfCourses: GolfCourse[] = [
  {
    id: "ko-olina-golf-club",
    name: "Ko Olina Golf Club",
    website: "https://www.koolinagolf.com/tee-times-and-rates/",
    address: "92-1220 Aliinui Dr, Kapolei, HI 96707",
    lat: 21.337,
    lng: -158.123,
    access: "Resort/Public",
    driveFromKoOlina: "3-8 min",
    price18: "Approx. $275 visitor / resort rates vary dynamically",
    price9: "Approx. $140 9 holes",
    twilight: "Approx. $210 after 1 PM; current site notes dynamic rates",
    rentalClubs: "Available; verify when booking",
    drivingRange: "Excellent practice facilities and warm-up basket noted by course",
    difficulty: "Intermediate",
    scenicRating: 5,
    beginnerRating: 4,
    familyRating: 5,
    duration: "9 holes 2-2.5 hr; 18 holes about 4 hr 20 min",
    bestTeeTime: "Early morning for cooler weather or later 9-hole window for a resort day",
    weatherWindNote: "Leeward side is usually drier; afternoon trade winds can still matter.",
    itineraryCompatibility: ["Wednesday flexible day", "Thursday resort day", "Departure morning if timing allows"],
    tags: ["Near Ko Olina", "Resort Luxury", "Practice Facilities", "Rental Clubs", "Most Convenient Option"],
    recommendationLabels: ["Closest to resort", "Best quick round", "Best logistics", "Most Convenient Option"],
    photo: oahuScenicPhoto,
    notes: "Most convenient option for this trip and easiest to fit around family resort time.",
    pricingUpdated: "Estimate checked May 2026; rates are dynamically updateable."
  },
  {
    id: "turtle-bay-golf-course",
    name: "Turtle Bay Golf",
    website: "https://www.turtlebayexperiences.com/things-to-do/golf",
    address: "57-091 Kamehameha Hwy, Kahuku, HI 96731",
    lat: 21.7034,
    lng: -157.9974,
    access: "Resort/Public",
    driveFromKoOlina: "65-85 min",
    price18: "Approx. $285 visitor / guest rates may start lower",
    price9: "Approx. $150 for 9 holes; guest rates may vary",
    twilight: "Check booking engine for current late-day pricing",
    rentalClubs: "Available; verify when booking",
    drivingRange: "Practice facilities available",
    difficulty: "Challenging",
    scenicRating: 5,
    beginnerRating: 3,
    familyRating: 4,
    duration: "9 holes 2-2.5 hr; 18 holes 4.5 hr",
    bestTeeTime: "Pair with North Shore day; early tee time or a planned separate golf morning",
    weatherWindNote: "North Shore wind can add challenge; surf-season traffic can slow return.",
    itineraryCompatibility: ["Monday North Shore day"],
    tags: ["Ocean Views", "Resort Luxury", "Challenging", "North Shore", "Rental Clubs"],
    recommendationLabels: ["Best ocean views", "Best scenic course", "Best for serious golfers"],
    photo: northShorePhoto,
    notes: "Arnold Palmer course feel with North Shore scenery and a luxury golf experience.",
    pricingUpdated: "Estimate checked May 2026; verify direct booking."
  },
  {
    id: "royal-hawaiian-golf-club",
    name: "Royal Hawaiian Golf Club",
    website: "https://www.royalhawaiiangc.com/",
    address: "770 Auloa Rd, Kailua, HI 96734",
    lat: 21.375,
    lng: -157.778,
    access: "Public",
    driveFromKoOlina: "55-75 min",
    price18: "Approx. $200 visitor rate",
    twilight: "Check direct booking for current late-day rates",
    rentalClubs: "Available; verify when booking",
    drivingRange: "Limited practice/warmup; verify current facilities",
    difficulty: "Challenging",
    scenicRating: 5,
    beginnerRating: 2,
    familyRating: 3,
    duration: "18 holes 4.5-5 hr",
    bestTeeTime: "Early morning on a Windward/Kailua side day",
    weatherWindNote: "Lush valley can be wet; check rain before committing.",
    itineraryCompatibility: ["Saturday Kailua side", "Tuesday Windward beach day"],
    tags: ["Jungle Course", "Mountain Views", "Challenging", "Scenic"],
    recommendationLabels: ["Best jungle experience", "Most visually unique", "Best mountain scenery"],
    photo: windwardPhoto,
    notes: "Dramatic Koʻolau/Jurassic-style setting; amazing visually, but not the easiest family round.",
    pricingUpdated: "Estimate checked May 2026; verify direct booking."
  },
  {
    id: "royal-kunia-country-club",
    name: "Royal Kunia Country Club, Inc.",
    website: "https://www.royalkuniacc.com/",
    address: "94-1509 Anonui St, Waipahu, HI 96797",
    lat: 21.393,
    lng: -158.032,
    access: "Public",
    driveFromKoOlina: "20-30 min",
    price18: "Varies; generally mid-island public-course pricing",
    twilight: "Check booking engine",
    rentalClubs: "Verify when booking",
    drivingRange: "Practice facilities; verify current availability",
    difficulty: "Intermediate",
    scenicRating: 4,
    beginnerRating: 4,
    familyRating: 4,
    duration: "18 holes about 4-4.5 hr",
    bestTeeTime: "Morning or twilight on a flexible/resort day",
    weatherWindNote: "Central ridge views; afternoon winds can pick up.",
    itineraryCompatibility: ["Wednesday flexible day", "Thursday resort day"],
    tags: ["Mountain Views", "Near Ko Olina", "Local Favorite", "Intermediate"],
    recommendationLabels: ["Best value near resort", "Best relaxed family round"],
    photo: oahuScenicPhoto,
    notes: "Good mid-island option with scenic elevation views and easier logistics than Windward/North Shore.",
    pricingUpdated: "Seasonal estimate; verify direct booking."
  },
  {
    id: "olomana-golf-links",
    name: "Olomana Golf Links",
    website: "https://olomanalinks.com/",
    address: "41-1801 Kalanianaʻole Hwy, Waimānalo, HI 96795",
    lat: 21.341,
    lng: -157.724,
    access: "Public",
    driveFromKoOlina: "60-80 min",
    price18: "Check current rates; course site notes operational changes",
    twilight: "Check current booking",
    rentalClubs: "Rental clubs listed at about $30 per set",
    drivingRange: "Driving range noted, but current site also flags closures; verify before going",
    difficulty: "Beginner-friendly",
    scenicRating: 4,
    beginnerRating: 5,
    familyRating: 4,
    duration: "9-hole/practice style 1-2.5 hr; full round 4 hr if available",
    bestTeeTime: "Windward beach day add-on only if currently open",
    weatherWindNote: "Windward showers possible; check same-day course status.",
    itineraryCompatibility: ["Tuesday Windward beach day", "Saturday Kailua side"],
    tags: ["Beginner Friendly", "Mountain Views", "Driving Range", "Local Favorite"],
    recommendationLabels: ["Best relaxed family round", "Best practice option"],
    photo: windwardPhoto,
    notes: "More casual/local feel and good for lower-pressure golf, but verify current open status.",
    pricingUpdated: "Course site checked May 2026; verify before planning."
  },
  {
    id: "kaneohe-klipper",
    name: "Kaneohe Klipper Golf Course",
    website: "https://hawaii.usmc-mccs.org/recreation-fitness/golf",
    address: "Kaneohe Bay Dr, MCBH, Kāneʻohe, HI 96734",
    lat: 21.449,
    lng: -157.761,
    access: "Military-affiliated",
    driveFromKoOlina: "55-75 min",
    price18: "Military/MCCS rates vary by eligibility",
    price9: "9-hole rates available for eligible players",
    twilight: "Twilight/sunset categories listed by MCCS",
    rentalClubs: "Verify with MCCS",
    drivingRange: "Practice facilities; verify access",
    difficulty: "Intermediate",
    scenicRating: 5,
    beginnerRating: 3,
    familyRating: 3,
    duration: "9 holes 2 hr; 18 holes 4-4.5 hr",
    bestTeeTime: "Only if access is confirmed; pair with Windward day",
    weatherWindNote: "Ocean wind and base access logistics are the key variables.",
    itineraryCompatibility: ["Saturday Kailua side", "Tuesday Windward beach day"],
    tags: ["Ocean Views", "Military-affiliated", "Challenging", "Windward"],
    recommendationLabels: ["Best ocean views if accessible"],
    photo: windwardPhoto,
    notes: "Incredible ocean-view course, but access is military-affiliated and must be confirmed.",
    pricingUpdated: "MCCS rate sheet checked May 2026; eligibility-dependent."
  },
  {
    id: "ala-wai-golf-course",
    name: "Ala Wai Golf Course",
    website: "https://alawairange.com/rates",
    address: "404 Kapahulu Ave, Honolulu, HI 96815",
    lat: 21.282,
    lng: -157.819,
    access: "Municipal",
    driveFromKoOlina: "40-65 min",
    price18: "Municipal rates; check official rate page",
    twilight: "Check official rate page",
    rentalClubs: "Verify with course/range",
    drivingRange: "Driving range available",
    difficulty: "Beginner-friendly",
    scenicRating: 3,
    beginnerRating: 5,
    familyRating: 4,
    duration: "Fast round possible depending on tee sheet",
    bestTeeTime: "Only if already going into Honolulu; keep the pairing local-food focused",
    weatherWindNote: "Urban course; less wind exposure than coastal courses.",
    itineraryCompatibility: ["Thursday local food day"],
    tags: ["More Affordable", "Beginner Friendly", "Driving Range", "Fast Round"],
    recommendationLabels: ["Best affordable/casual option"],
    photo: oahuScenicPhoto,
    notes: "Affordable/casual option, but lower priority because it pulls the trip into town.",
    pricingUpdated: "Verify official municipal rates."
  },
  {
    id: "mililani-golf-club",
    name: "Mililani Golf Club",
    website: "https://mililanigolf.com/rates/",
    address: "95-176 Kuahelani Ave, Mililani, HI 96789",
    lat: 21.452,
    lng: -158.01,
    access: "Public",
    driveFromKoOlina: "35-45 min",
    price18: "Approx. $63-$73 public club play shown on course rate page",
    twilight: "Check direct booking",
    rentalClubs: "Verify when booking",
    drivingRange: "Practice facilities; verify current availability",
    difficulty: "Beginner-friendly",
    scenicRating: 3,
    beginnerRating: 5,
    familyRating: 4,
    duration: "18 holes 4 hr; quicker windows may be available",
    bestTeeTime: "Morning or twilight on a flexible day",
    weatherWindNote: "Central location; usually straightforward weather compared with windward valley courses.",
    itineraryCompatibility: ["Wednesday flexible day", "North Shore transit"],
    tags: ["More Affordable", "Beginner Friendly", "Local Favorite"],
    recommendationLabels: ["Best value", "Best relaxed family round"],
    photo: northShorePhoto,
    notes: "Good affordable/casual option with central route compatibility.",
    pricingUpdated: "Rate page checked May 2026; verify direct booking."
  },
  {
    id: "moanalua-golf-club",
    name: "Moanalua Golf Club",
    website: "https://www.moanaluagolfclub.com/",
    address: "1250 Ala Aolani St, Honolulu, HI 96819",
    lat: 21.356,
    lng: -157.894,
    access: "Semi-private",
    driveFromKoOlina: "25-40 min",
    price18: "Check direct booking",
    twilight: "Check direct booking",
    rentalClubs: "Verify when booking",
    drivingRange: "Verify current facilities",
    difficulty: "Beginner-friendly",
    scenicRating: 3,
    beginnerRating: 4,
    familyRating: 4,
    duration: "Shorter/casual round possible",
    bestTeeTime: "Flexible day or airport-side timing",
    weatherWindNote: "Central/Honolulu valley weather; check rain.",
    itineraryCompatibility: ["Arrival/departure timing", "Wednesday flexible day"],
    tags: ["More Affordable", "Fast Round", "Local Favorite"],
    recommendationLabels: ["Best quick round", "Best casual option"],
    photo: oahuScenicPhoto,
    notes: "Casual option for golfers who want lower-pressure logistics than resort courses.",
    pricingUpdated: "Verify direct booking."
  }
];

export const activityFilters = [
  "Easy",
  "Teen friendly",
  "Waterfall",
  "Beach",
  "Low crowds",
  "Early morning",
  "Relaxing",
  "Adventure",
  "Scenic"
];

export const sampleComments: TripComment[] = [
  {
    id: "c1",
    itemId: "sat-kailua",
    author: "Aunt Lisa",
    text: "Voting Kailua over Lanikai if parking looks stressful. I want beach time, not parking drama.",
    reaction: "🌊",
    interest: "must-do",
    createdAt: new Date("2026-05-01T10:00:00").toISOString()
  },
  {
    id: "c2",
    itemId: "mon-north-shore",
    author: "Maya",
    text: "Can Ululani's be non-optional? Asking for science.",
    reaction: "🍧",
    interest: "must-do",
    createdAt: new Date("2026-05-02T12:00:00").toISOString()
  },
  {
    id: "c3",
    itemId: "tue-lulumahu-review",
    author: "Dad",
    text: "Early start is fine if coffee is acquired within the first hour.",
    reaction: "☕",
    interest: "interested",
    createdAt: new Date("2026-05-03T08:30:00").toISOString()
  }
];

export const sampleSuggestions: Suggestion[] = [
  {
    id: "s1",
    author: "Nana",
    title: "Book one sunset dinner near Ko Olina",
    category: "food",
    notes: "Nice way to avoid a long drive after a full day.",
    votes: { "❤️": 5, "👍": 2 },
    createdAt: new Date("2026-05-04T09:00:00").toISOString()
  },
  {
    id: "s2",
    author: "Jake",
    title: "Add a snorkeling conditions check before Shark's Cove",
    category: "beach",
    notes: "Only go in if the water is calm. Otherwise it can be a look-around stop.",
    votes: { "👍": 4, "🌊": 3 },
    createdAt: new Date("2026-05-04T11:00:00").toISOString()
  },
  {
    id: "s3",
    author: "Mom",
    title: "Memory wall prompt: favorite bite of the day",
    category: "memory",
    notes: "Everyone adds one photo or caption each night.",
    votes: { "📸": 6 },
    createdAt: new Date("2026-05-05T14:00:00").toISOString()
  }
];

export const packingItems = [
  "Reef shoes",
  "Beach towels",
  "Hiking shoes",
  "Snorkel gear",
  "Phone chargers",
  "Reef-safe sunscreen",
  "Water bottles",
  "Hats",
  "Light rain jacket",
  "Dry bag"
];
